### ISSUE TITLE
Error getting AQI from Aeris weather. The error was: string indices must be integers

### ISSUE THREAD

**Issue by roe-dl** [roe-dl/weewx-DWD#11]
Kurze Frage nebenbei, würde das den Fehler beheben / erklären?

```
message repeated 15 times: [ ERROR user.belchertown: Error getting AQI from Aeris weather. The error was: string indices must be integers]
ERROR user.belchertown: Error getting AQI from Aeris weather. The error was: string indices must be integers
```

_Originally posted by @c0by85 in https://github.com/roe-dl/weewx-DWD/discussions/10#discussioncomment-2294292_

**Comment by roe-dl** [comment]
Ich habe mal einen Branch AQI angelegt und den Vorschlag eingefügt: 17f57887a67f227164cde06e7a87170b545caed3

**Comment by c0by85** [comment]
Und wie weiter? Soll ich mit dem anderen Branch mal testen? Einfach darüber kopieren? Sorry ist "Neuland" 😆

**Comment by roe-dl** [comment]
Ich habe auch schon überlegt, dort eine direkte Abfrage der AQI-Daten bei Aeris einzubauen. So kompliziert ist das ja nicht, zumal wenn man das Vorbild hat.

**Comment by roe-dl** [comment]
> Und wie weiter? Soll ich mit dem anderen Branch mal testen? Einfach darüber kopieren? Sorry ist "Neuland" 😆

Ein Branch wird typischerweise angelegt, wenn man einen Gedanken oder eine Idee testen will. Am Ende kann man sie in den Haupt-Branch einfügen oder eben auch nicht. Ein Branch läßt sich genau so herunterladen. Man bekommt dabei auch alle anderen Dateien.

**Comment by hoetzgit** [comment]
> Ich habe auch schon überlegt, dort eine direkte Abfrage der AQI-Daten bei Aeris einzubauen. So kompliziert ist das ja nicht, zumal wenn man das Vorbild hat.

das wäre optimal :-)

**Comment by hoetzgit** [comment]
Hab jetzt ein bisschen den Code am Handy angeschaut und habe zwei Fragen. Funktionieren Zeilen `442..443` wenn vorher evtl. Zeile `441` ausgeführt wird? 
Funktioniert das Auslesen der API Zugangsdaten auch, wenn diese z.B. im Verzeichnis `lang/de.conf` konfiguriert werden?
Danke für die Anpassungen, morgen teste ich dann gleich mal

**Comment by roe-dl** [comment]
> Hab jetzt ein bisschen den Code am Handy angeschaut und habe zwei Fragen. Funktionieren Zeilen `442..443` wenn vorher evtl. Zeile `441` ausgeführt wird?

Berechtigter Einwand. Das muß ich korrigieren.

> Funktioniert das Auslesen der API Zugangsdaten auch, wenn diese z.B. im Verzeichnis `lang/de.conf` konfiguriert werden?

Da gehören sie definitiv nicht hin. In die Sprachdateien gehören keine individuellen Konfigurationen. Das gehört nach `weewx.conf` oder zur Not noch `skin.conf`.

> Danke für die Anpassungen, morgen teste ich dann gleich mal

Ich habe bei mir nur kurz probiert, ob es die Aeris-Daten lädt. Das hat es getan. Feinheiten sind auf jeden Fall noch offen.

**Comment by c0by85** [comment]
Log sieht sauber aus und AQI Daten werden abgerufen. :+1: :+1: :+1:

**Comment by roe-dl** [comment]
Ich mache noch eine Konfigurationsoption, damit man es an- und abschalten kann, und kommt es nach master zurück.

**Comment by roe-dl** [comment]
Mit Commit f8a87f7c9b5de568cd95e18c9b74d4a7f5665a9a ist diese Option nun eingefügt. Sie lautet `--aqi-source` in der Kommandozeile oder `aqi_source` in `weewx.conf`. Der Wert kann entweder `None` (kein AQI-Abschnitt) oder  `aeris` (Abfrage von Aeris) sein. Mit der Art der Option vorbereitet ist, das Umweltbundesamt als weitere Quelle hinzufügen zu können.

**Comment by roe-dl** [comment]
Es geht jetzt wieder in der `master`-Branch weiter.
