### ISSUE TITLE
Option zum Ein- / Ausblenden vom Ortsnamen / Placemark

### ISSUE THREAD

**Issue by c0by85** [roe-dl/weewx-DWD#13]
Kann evtl. noch eine Option mit eingebaut werden, das man vll. mit `--hide-placemark` o.ä., den Ortsnamen / Placemark beim Wetterbericht ausblenden kann? Aktuelle kommentiere ich immer folgende Zeile aus.

`s += '<p itemscope itemtype="https://schema.org/Place"><strong itemprop="name">%s</strong></p>\n' % placemark['description']`

**Comment by roe-dl** [comment]
Erledigt.

**Comment by hoetzgit** [comment]
Ich bekomme bei Aufruf:

`/usr/local/bin/weewx-DWD/dwd-mosmix --config=/home/weewx/weewx.conf --verbose --hide-placemark 10688
`

diese Ausgabe:

```
Usage: dwd-mosmix [options]

dwd-mosmix: error: no such option: --hide-placemark

```

**Comment by hoetzgit** [comment]
> Ich bekomme bei Aufruf:
> 
> `/usr/local/bin/weewx-DWD/dwd-mosmix --config=/home/weewx/weewx.conf --verbose --hide-placemark 10688 `
> 
> diese Ausgabe:
> 
> ```
> Usage: dwd-mosmix [options]
> 
> dwd-mosmix: error: no such option: --hide-placemark
> ```

Bitte ignorieren, wenn man zu blöd ist den aktuellen Code zu benutzen ...

**Comment by c0by85** [comment]
> Erledigt.

Teste ich später sehr gerne.
