### ISSUE TITLE
Some really minor layout issues

### ISSUE THREAD

**Issue by olwaldi** [roe-dl/weewx-DWD#17]
1. The table with hourly forecast doesn't include min/max temperatures (wouldn't make sense of course). But as a side effect the first column is a little bit smaller compared with forecast daily. If including both tables, their columns are no longer aligned. It would be nice (but maybe difficult), if the first columns would have the same widths. BTW you can see my "problem" also on your weather station https://www.woellsdorf-wetter.de/forecast/doebeln.html
2. Currently the created HTML output forecast-*-*.inc is neither indented nor uses much linebreaks. It would be nice to output the HTML with human readable indentation (2 blanks per indentation level - sadly I could't fool git to include unrendered HTML sample code here). That might easy debugging.

Regards, Michael

**Comment by roe-dl** [comment]
As there are no further comments, I close this issue now.
