### ISSUE TITLE
No warnings displayed

### ISSUE THREAD

**Issue by msman0** [roe-dl/weewx-DWD#22]
Hi, the system works fine last weeks but now we have warnings (in warnings.json) but they are not displayed. Is these a general issue?
Thank you.
Regards,
Martin

```
dwd:
/usr/local/bin/dwd-warnings 2>/dev/null >/dev/null
```

```
[DeutscherWetterdienst]
    path = /etc/weewx/skins/neowx-material/dwd
    [[warning]]
        icons = ../neo/dwd/warn_icons_50x50
        states = Bayern
        [[[counties]]]
            Kreis Miltenberg = BY
```

**Comment by msman0** [comment]
Here ist the files which display no warning:
[20220522_2340warnings-nok.zip](https://github.com/roe-dl/weewx-DWD/files/8757328/20220522_2340warnings-nok.zip)
And here the file with warning:
[20220523_2040warnings-ok.zip](https://github.com/roe-dl/weewx-DWD/files/8757330/20220523_2040warnings-ok.zip)

Is there no warning if level 1 or should they warn every time when the selected region is in the json file?

**Comment by roe-dl** [comment]
I will have a look at it.

**Comment by roe-dl** [comment]
The warnings file provided by the DWD contains of two sections: warnings and preliminary information ("Vorabinformation Unwetter"). The entries you are missing are in the preliminary information section. This section is not included. To include it you could add

```
        wrn.update(vrb)
```

in line 124 of `/usr/local/bin/dwd-warnings`. That is before the line

```
        region={}
```

It's arguable to include or not to include the preliminary information entries. So I am not sure what would be better and what the users would expect.
