### ISSUE TITLE
DwdMosmix' object has no attribute 'belchertown_compasslang

### ISSUE THREAD

**Issue by jimm2905** [roe-dl/weewx-DWD#40]
dwd-mosmix --weewx --belchertown --verbose --open-meteo=gem 48.22,-89.19
Using configuration file /etc/weewx/weewx.conf
-- configuration data ----------------------------------
log success:       True
log failure:       True
target path:       /home/weewx/skins/Belchertown/dwd
horiz. tab:        True
vertical tab:      True
icon set:          4
station location:  
aeris api id:      None
aeris api secret:  None
SQLITE_ROOT:       /home/weewx/conf
--------------------------------------------------------
successfully downloaded https://api.open-meteo.com/v1/gem?latitude=48.22&longitude=-89.19&hourly=temperature_2m,relativehumidity_2m,dewpoint_2m,pressure_msl,cloudcover,cloudcover_low,cloudcover_mid,cloudcover_high,windspeed_10m,winddirection_10m,windgusts_10m,weathercode&timeformat=unixtime
what to output: ['belchertown']
start loop over placemarks
process placemark id "openmeteo-48.22--89.19-gem" name "48.22 -89.19"
...
belchertown
geo file '/home/weewx/skins/Belchertown/dwd/geo-openmeteo-48.22--89.19-gem.json' succuessfully loaded
now 19:29:38 timestep 20:00:00
Traceback (most recent call last):
  File "/usr/local/bin/dwd-mosmix", line 2452, in <module>
    dwd.forecast_all(mmos,output,options.dry_run,lang=options.lang)
  File "/usr/local/bin/dwd-mosmix", line 2077, in forecast_all
    self.forecast_placemark(placemark, mos['ForecastTimeSteps'], issue, output, dryrun, lang)
  File "/usr/local/bin/dwd-mosmix", line 2053, in forecast_placemark
    self.belchertown(placemark,days,recs3hr,timesteps,daynights,issue,dryrun)
  File "/usr/local/bin/dwd-mosmix", line 1334, in belchertown
    'windDir':compass(nround(placemark['Forecast']['DD'][idx]),self.belchertown_compasslang,False),
AttributeError: 'DwdMosmix' object has no attribute 'belchertown_compasslang'

weewx.conf (snippet)
################################################################################
[DeutscherWetterdienst]
[WeatherServices]
    path='/home/weewx/skins/Belchertown/dwd'
    [[current]]
        [[[ThisStation]]]
            # actual readings out of the forecast for the location of this station
            debug = 3
            provider = Open-Meteo
            model = gem_regional
            prefix = om
    [[forecast]]
        icons='../images'
        orientation=h,v
        show_obs_symbols = True # optional
        show_obs_description = False # optional
        show_placemark = True # optional

##############################################################################

Any tips or pointers?

**Comment by roe-dl** [comment]
To use the `--belchertown` option a special configuration section is required.

```
[DeutscherWetterdienst]
    [[Belchertown]]
        section = Belchertown
        warnings = None
        forecast = openmeteo-48.22--89.19-gem

```

**Comment by roe-dl** [comment]
I added some additional explanation in the [English README](https://github.com/roe-dl/weewx-DWD/blob/master/README-en.md).

**Comment by jimm2905** [comment]
root@myweewx:~/skins/Belchertown/dwd# dwd-mosmix --weewx --html --hourly --verbose --lang=en --open-meteo=gem 48.22,-89.19
Using configuration file /etc/weewx/weewx.conf
-- configuration data ----------------------------------
log success:       True
log failure:       True
target path:       /home/weewx/skins/Belchertown/dwd
horiz. tab:        True
vertical tab:      True
icon set:          4
station location:  lat XX.491 lon -YY.689 alt 369.1128
aeris api id:      
aeris api secret:  
SQLITE_ROOT:       /home/weewx/conf
--------------------------------------------------------
successfully downloaded https://api.open-meteo.com/v1/gem?latitude=48.22&longitude=-89.19&hourly=temperature_2m,relativehumidity_2m,dewpoint_2m,pressure_msl,cloudcover,cloudcover_low,cloudcover_mid,cloudcover_high,windspeed_10m,winddirection_10m,windgusts_10m,weathercode&timeformat=unixtime
what to output: ['hourly', 'html']
start loop over placemarks
process placemark id "openmeteo-48.22--89.19-gem" name "48.22 -89.19"
...
output hourly forecast
night=False ww=(1, 'Bewölkung abnehmend 20%', 'Clouds generally dissolving or becoming less developed 20', 28, 'mostly-clear-day.png', '2-8.png', 'fair', '::FW')
night=False ww=(1, 'Bewölkung abnehmend 22%', 'Clouds generally dissolving or becoming less developed 22', 28, 'mostly-clear-day.png', '2-8.png', 'fair', '::FW')
night=False ww=(0, 'keine Bewölkungsentwicklung 0%', 'no cloud cover development 0', 29, 'clear-day.png', '0-8.png', 'clear', '::CL')
night=False ww=(0, 'keine Bewölkungsentwicklung 0%', 'no cloud cover development 0', 29, 'clear-day.png', '0-8.png', 'clear', '::CL')
night=True ww=(0, 'keine Bewölkungsentwicklung 0%', 'no cloud cover development 0', 29, 'clear-night.png', '0-8.png', 'clear', '::CL')
night=True ww=(0, 'keine Bewölkungsentwicklung 0%', 'no cloud cover development 0', 29, 'clear-night.png', '0-8.png', 'clear', '::CL')
night=True ww=(0, 'keine Bewölkungsentwicklung 0%', 'no cloud cover development 0', 29, 'clear-night.png', '0-8.png', 'clear', '::CL')
night=True ww=(0, 'keine Bewölkungsentwicklung 2%', 'no cloud cover development 2', 29, 'clear-night.png', '0-8.png', 'clear', '::CL')
night=True ww=(0, 'keine Bewölkungsentwicklung 11%', 'no cloud cover development 11', 29, 'mostly-clear-night.png', '0-8.png', 'fair', '::FW')
night=True ww=(0, 'keine Bewölkungsentwicklung 6%', 'no cloud cover development 6', 29, 'clear-night.png', '0-8.png', 'clear', '::CL')
night=True ww=(0, 'keine Bewölkungsentwicklung 5%', 'no cloud cover development 5', 29, 'clear-night.png', '0-8.png', 'clear', '::CL')
Traceback (most recent call last):
  File "/usr/local/bin/dwd-mosmix", line 2452, in <module>
    dwd.forecast_all(mmos,output,options.dry_run,lang=options.lang)
  File "/usr/local/bin/dwd-mosmix", line 2077, in forecast_all
    self.forecast_placemark(placemark, mos['ForecastTimeSteps'], issue, output, dryrun, lang)
  File "/usr/local/bin/dwd-mosmix", line 2043, in forecast_placemark
    self.write_html(placemark,timesteps,daynights,['TTT','FF','DD','RR1c','R101','PPPP','Rad1h'],dryrun,range=11,lang=lang)
  File "/usr/local/bin/dwd-mosmix", line 909, in write_html
    for idx,jj in enumerate(placemark['Forecast'][ii]):
KeyError: 'RR1c'

root@myweewx:~/skins/Belchertown/dwd# dwd-mosmix --weewx --json --hourly --verbose --lang=en --open-meteo=gem 48.22,-89.19
Using configuration file /etc/weewx/weewx.conf
-- configuration data ----------------------------------
log success:       True
log failure:       True
target path:       /home/weewx/skins/Belchertown/dwd
horiz. tab:        True
vertical tab:      True
icon set:          4
station location:  lat XX.491 lon -YY.689 alt 369.1128
aeris api id:      
aeris api secret:  
SQLITE_ROOT:       /home/weewx/conf
--------------------------------------------------------
successfully downloaded https://api.open-meteo.com/v1/gem?latitude=48.22&longitude=-89.19&hourly=temperature_2m,relativehumidity_2m,dewpoint_2m,pressure_msl,cloudcover,cloudcover_low,cloudcover_mid,cloudcover_high,windspeed_10m,winddirection_10m,windgusts_10m,weathercode&timeformat=unixtime
what to output: ['hourly', 'json']
start loop over placemarks
process placemark id "openmeteo-48.22--89.19-gem" name "48.22 -89.19"
...
calculate daily forecast
calculate 3hr forecast
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
'T5cm'
'VV'
'R101'
json
placemark id "openmeteo-48.22--89.19-gem" processed
end loop over placemarks
No error message

![1Hr_forecast](https://user-images.githubusercontent.com/124475187/216851926-1d250dfb-1865-4b1c-a0ad-2e1fa85c35a6.jpg)
![3hr_forecast](https://user-images.githubusercontent.com/124475187/216851929-a8919b07-de43-40c1-b654-c60df25c133d.jpg)
![24hr_forecast](https://user-images.githubusercontent.com/124475187/216851933-ac181db2-419c-4cb0-932e-f6eacb58d07b.jpg)
[forecast.zip](https://github.com/roe-dl/weewx-DWD/files/10614105/forecast.zip)

**Comment by roe-dl** [comment]
Which temperature unit do you use?

**Comment by roe-dl** [comment]
Could you provide a link to your website? I would like to see live what happens.

**Comment by jimm2905** [comment]
Try http://munro.homeip.net:8080/belchertown/
Not normally on web but will post it for a while and also not https.
Also sent a forecast.json as a zip file earlier below pics of forecast

**Comment by roe-dl** [comment]
Actually the forecast is configured to US units.

Please, set `forecast_units = si` in `skin.conf` or `weewx.conf`. The value in `weewx.conf` takes precedence over the value in `skin.conf`. The value in `skin.conf` comes into effect immediately, while the value in `weewx.conf` requires a restart to come into effect. 

If you want to use US units, please download the last version of `dwd-mosmix` as I added support for US units only today.

**Comment by jimm2905** [comment]
Thanks.  That fixed most of it.  Any ideas on  the pop (probability of precip)?  I assume that is the little droplet below hi and lo temp.
Can't see it being 0 for the entire forecast.  Environoment Canada site is here https://weather.gc.ca/city/pages/on-100_metric_e.html and pop is in % just below the hi temp for the day.

**Comment by jimm2905** [comment]
I tested the US units forecast and the windspeeds still seem to be in kmph.  Temps ok.  Still issue with pop.
![us_units_forecast](https://user-images.githubusercontent.com/124475187/217157960-0e2b9fff-696e-495e-99ab-54cfa74adfe4.jpg)

**Comment by roe-dl** [comment]
Pop is actually not provided by Open-Meteo. I asked them to include it and I am now waiting for their reply.

**Comment by jimm2905** [comment]
OK. Thanks!
