### ISSUE TITLE
Fehlermeldung bzgl. belchertown von dwd_mosmix

### ISSUE THREAD

**Issue by olwaldi** [roe-dl/weewx-DWD#45]
Beim Aufruf von dwd-mosmix
`dwd-mosmix --hourly --daily --icon-set=dwd --weewx K2714
`
gibts immer Fehlermeldungen bzgl. Belchertown, das ich nicht nutze (und somit auch nicht in weew.conf konfiguriert habe). Mit der alten Version von dwd_mosmix tuts.

In weewx.conf ist DWD wie folgt konfiguriert (leider wird Code nicht als Code übernommen:-():
`# settings for DWD
[DeutscherWetterdienst]
    path = /etc/weewx/skins/Seasons_DWD/dwd

    [[warning]]
        icons = icons/warn
        states = Baden-Württemberg
        [[[counties]]]
            Kreis Ludwigsburg = KL
        [[[cities]]]
            Stadt Ludwigsburg = SL
    [[forecast]]
        icons = icons/wetter
        orientation = h
`

Die Fehlermeldung lautet:
Using configuration file /etc/weewx/weewx.conf
ERROR Belchertown config KeyError WeatherServices

Ich habe dann versucht (wie im README beschrieben), VOR den forecast-Eintrag einen WeatherServices-Eintrag zu machen:
`[WeatherServices]                                       
 
    Verzeichnis, in das die Dateien gespeichert werden sollen
    path=/etc/weewx/skins/Seasons_DWD/dwd                               
    # Stuttgart-Echterdingen                                   
    [[current]]                                                
        [[[04931]]]                                              n
            provider = DWD                                     
            model = CDC                                        
            prefix = observation_type_prefix_for_station       
            # equipment of the weather station (optional)      
            observations = air,wind,gust,precipitation,solar   
`

so daß forecast dann unterhalb von WeatherServices steht. Gibt eine ähnliche Fehlermeldung, dann mit KeyError section.

Was mache ich falsch?

Mein Ziel ist eigentlich nur, erstmal das neue dwd_mosmix mit den alten Settings ans Laufen zu kriegen. Danach will ich die Option --database dazunehmen. Die Erwartung wäre, daß in der Datenbank Vorhersagedaten für K2714 abgelegt werden. D.h. ich will eigentlich gar keine Daten vom Stuttgarter Flughafen abrufen.

**Comment by roe-dl** [comment]
a) Der Abschnitt `[WeatherServices]` **muss** existieren.
b) Es funktioniert auch mit der Fehlermeldung. Ich werde es trotzdem korrigieren, daß die Meldung nicht mehr auftritt.

**Comment by roe-dl** [comment]
Wahrscheinlich fehlt die Option `--html` oder `--json`.

**Comment by olwaldi** [comment]
Yep. Das war's. Mit --html tut's wieder.

Danke für die schnelle Hilfe, Michael
