### ISSUE TITLE
Vorhersagedaten um berechnete Größen erweitern

### ISSUE THREAD

**Issue by olwaldi** [roe-dl/weewx-DWD#48]
weewx kann aus Wetterdaten abgeleitete Größen berechnen wie z.B. windchill. Die berechneten Daten werden in der weewx-sqlite-Datenbank gespeichert (und nicht dynamisch bei Bedarf berechnet).

Daher meine Anregung: Bitte in die forecast-sqlite-Datenbank auch die "berechenbaren" Größen mit aufnehmen, konkret wäre das vermutlich nur windchill. Die Formeln dafür sind in bin/weewx/wxformulas.py. Ich hatte versucht, in skin.conf die Berechnung durchzuführen, aber Python-Routinen kann man dort nicht aufrufen.

**Comment by roe-dl** [comment]
Bitte prüfen.

**Comment by olwaldi** [comment]
Funktioniert, d.h. id der DB werden windchill-Daten eingepflegt. Allerdings wundert mich, daß windchill GRÖSSER ist als outTemp. Da hätte ich eine Absenkung erwartet. Anbei die forecat-DB.
[dwd-forecast-K2714.sdb.gz](https://github.com/roe-dl/weewx-DWD/files/12670265/dwd-forecast-K2714.sdb.gz)

**Comment by roe-dl** [comment]
Ich sehe mir die Berechnung nochmal an.

**Comment by roe-dl** [comment]
Ich habe die in `wxformulas.py` angegebene Gleichung für Grad Fahrenheit und Meilen pro Stunde in eine Gleichung für Grad Celsius und Kilometer pro Stunde umgerechnet. Dabei kommen mit geringer Abweichung die Faktoren heraus, die in dem Wikipedia-Artikel genannt sind und die der Berechnung hier zugrundeliegen. Einen Fehler kann ich im Moment nicht entdecken.

**Comment by roe-dl** [comment]
Davis schreibt in der technischen Dokumentation zur Vantage Pro Folgendes:

> Newer product revisions (WeatherLink version 5.1 and Vantage Pro consoles with Sept 7, 2001 firmware and later) are based on the following formula:
> 35.74 + 0.6215T - 35.75 * (V 0.16 ) + 0.4275T * (V 0.16 )
> As with the old formula, any place where the result yields a wind chill temperature greater than the air temperature, the wind chill is set equal to the air temperature. This always occurs at wind speeds of 0 mph or temperatures above 76°F. This also occurs at lower wind speeds with temperatures between 0°F and 76°F.

Daß die Formel Werte oberhalb der Lufttemperatur liefern kann, ist also normal. Es ist übrigens dieselbe Formel wie in `wxformulas.py`. Die Lösung, die Davis nutzt, taugt auch hier.

**Comment by olwaldi** [comment]
Ich habe auch etwas gegoogelt - windchill größer als Außentemperatur ist durchaus möglich. Und die aktuellen windchill-Werte passen recht gut zu den vorhergesagten.

Vielen Dank, Michael

**Comment by olwaldi** [comment]
Bei mir ist heatindex in der DB immer NULL. Aber das könnte daran liegen, daß die outTemp aktuell deutlich unter 26.7 liegt. Vorhersage für humidity funktioniert.

**Comment by roe-dl** [comment]
Es ist in der Tat so, daß die Werte nur berechnet werden, wenn die Temperatur über 26,7°C liegt. Anderenfalls ist der Wert `None` bzw. in der Datenbank `NULL`. Gestern hatte ich beim Ausprobieren noch kurz Gelegenheit, einen Wert zu sehen.
