### ISSUE TITLE
Parameter --belchertown zeigt in der 3H Ansicht keine maximale Windgeschwindigkeit

### ISSUE THREAD

**Issue by hoetzgit** [roe-dl/weewx-DWD#5]
Hallo, bei mir wird in der 3H Ansicht der Vorhersage keine maximale Windgeschwindigkeit angezeigt (Platzhalter Wert "NaN").

Ein testweises Einfügen in `dwd-mosmix`  z.B. nach Zeile `1120` von `'windGustKPH':rec['FFmax'],` behebt den Fehler.

ach ja, und bitte nicht denken ich meckere über noch nicht fertigen Code, ich möchte nur unterstützen ;-)

**Comment by roe-dl** [comment]
Übrigens: Ich glaube, jeder Entwickler freut sich über freiwillige Tester.

**Comment by hoetzgit** [comment]
`Für meine Begriffe müßte das FX3 oder ggf. FX1max sein`

Das kann natürlich sein, habe mich inhaltlich an der Zuweisung in Zelle 1120 orientiert und geschaut, welches Feld fehlte. Morgen möchte ich mir mal den Niederschlag in der 3H Ansicht ansehen, da ist bei mir überall 0%, obwohl in den anderen Ansichten >0.

Wie kann ich denn vermeiden hier "Fehler" zu posten, die evtl. schon erkannt und in der Entwicklung bereits behoben sind, bzw. bei Funktionen die noch nicht fertig entwickelt sind?

**Comment by roe-dl** [comment]
Es ist nicht so schlimm, wenn Fehler doppelt gepostet werden. Und der Hinweis auf FX3 und FX1 war von meiner Seite eher als Rückfrage zu verstehen. 

Ich habe jetzt FX3 genommen. Wenn es keine Proteste von Anwenderseite gibt, würde ich es so lassen.
