### ISSUE TITLE
By using the --open-meteo option i get the following error

### ISSUE THREAD

**Issue by lolijrhook** [roe-dl/weewx-DWD#50]
root@ucs:/etc/weewx/skins/weewx-wdc/dwd# dwd-mosmix --weewx --open-meteo=metno --json -v
Using configuration file /etc/weewx/weewx.conf
-- configuration data ----------------------------------
log success:       True
log failure:       True
target path:       /etc/weewx/skins/weewx-wdc/dwd
horiz. tab:        True
vertical tab:      True
icon set:          5
station location:  lat 51.84 lon 4.64 alt -3.0
aeris api id:     
aeris api secret:  
SQLITE_ROOT:       /etc/weewx/skins/weewx-wdc/dwd
--------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/dwd-mosmix", line 2571, in <module>
    lat = float(loc[0])
ValueError: could not convert string to float: 'Döbeln'

what can i do to get it right

**Comment by roe-dl** [comment]
There is the location missing on the command line. Try:

```
dwd-mosmix --weewx --open-meteo=metno --json -v 51.84,4.64
```

**Comment by lolijrhook** [comment]
It works
