### ISSUE TITLE
Missing warnicons

### ISSUE THREAD

**Issue by olwaldi** [roe-dl/weewx-DWD#51]
Just a minor issue... Currently there is a pre warning for heavy rain. But the corresponding icon is missing within warn icons (as linked within the main description. The missing file is warn_icons_gewitter_pre.png.

Please update the warn icon zip file.

**Comment by roe-dl** [comment]
Those Icons are provided by the German Weather Service DWD. The link directly links to their site. I am not the DWD. I cannot change files on their website. 

But you can see if [that link](https://www.woellsdorf-wetter.de/dwd/warn_icons_50x50/warn_icons_gewitter_pre.png) helps you.

**Comment by olwaldi** [comment]
Thank you very much. I was not aware that the zip file is a direct link into DWD. Probabely that file itself is outdated (from ~ 2016).

Regards, Michael
