### ISSUE TITLE
Download error 404

### ISSUE THREAD

**Issue by msman0** [roe-dl/weewx-DWD#52]
Hallo, bei mir wird seit dem Nachmittag keine Aktualisierung mehr durchgeführt.

Im Logfile habe ich folgendes gefunden:

`https://www.dwd.de/DWD/warnungen/warnapp/json/warnings.json
Auflösen des Hostnamens www.dwd.de (www.dwd.de)… 141.38.3.62
Verbindungsaufbau zu www.dwd.de (www.dwd.de)|141.38.3.62|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 404 Not Found
2023-06-23 00:17:22 FEHLER 404: Not Found.`

Wie kann der Fehler behoben werden?
Danke!

**Comment by c0by85** [comment]
Hängt evtl. hiermit zusammen. Es gibt aktuell auch keine Radarbilder für z.B. Brandenburg unter https://www.dwd.de/DWD/wetter/radar/rad_bbb_akt.jpg.

![image](https://github.com/roe-dl/weewx-DWD/assets/25707747/2fc1041a-8da6-4c8f-b313-396687bd2475)

**Comment by roe-dl** [comment]
Der DWD hat gestern eine Meldung herausgegeben, daß seine Internetseite kaputt ist. Sie arbeiten mit Hochdruck dran, stand bei Mastodon zu lesen.

https://mastodon.social/@DeutscherWetterdienst@social.bund.de/110587343293432585

Inzwischen geht es wieder.

**Comment by msman0** [comment]
Vielen Dank, geht bei mir jetzt auch wieder!
