### ISSUE TITLE
Koordinaten, die für Belchertown-Ausgabe bei der Abstandsbestimmung und bei AQI verwendet werden.

### ISSUE THREAD

**Issue by roe-dl** [roe-dl/weewx-DWD#56]
mosmix scheint AQI über Aeris abzurufen.
`INFO successfully downloaded https://api.aerisapi.com/airquality/closest?p=52.152493,9.929383&format=json&radius=50mi&limit=1&client_id=zyx&client_secret=xyz`
Hier werden wohl die fixen Koordinaten der Wetterstation verwendet. 

Kann man dies in dem `dwd-mosmix-call.sh.tmpl` fixen? [Edit: habe eben `# command 'aqi' converts to Belchertown format` in `dwd-mosmix` gefunden und damit denke ich ... nein]

Oder sollte man etwas in `dwd-mosmix` verändern?
````
    def download_aeris(self, what):
        if what=='aqi':
            url = (
                "https://api.aerisapi.com/airquality/closest?p=%s,%s&format=json&radius=50mi&limit=1&client_id=%s&client_secret=%s"
                % (self.latitude, self.longitude, self.forecast_api_id, self.forecast_api_secret)
                )
        else:
            return []
````
Ich glaube, dies ist das erste Mal das `self.latitude` auftaucht:
````
        # almanac
        stn = config_dict.get('Station',dict())
        self.latitude = float(stn.get('latitude'))
        self.longitude = float(stn.get('longitude'))
````

_Originally posted by @teffi71 in https://github.com/roe-dl/weewx-DWD/discussions/30#discussioncomment-7478348_

**Comment by teffi71** [comment]
Vielleicht hatte ich es noch nicht genau formuliert. ;)
`dwd-mosmix` kann fuer beliebige Koordinaten (lat/lon) per `--open-meteo` eine Wettervorhersage abrufen.
Mit `--aqi-source=aeris` kann man den Provider fuer AQI auswählen.

Aber - wie kann ich AQI fuer eine beliebige Koordinate (lat/lon) mit `dwd-mosmix` abrufen? Gibt es dafür bereits eine Möglichkeit?

Wenn ich `sudo dwd-mosmix --weewx --belchertown --html --daily --hourly --open-meteo=icon_global 52.152563,9.929290 --aqi-source=aeris` ausführe, wird der AQI nicht fuer `$current` geladen, sondern fuer die Koordinaten der Wetterstation von der Erstinstallation abgespeichert unter `$station`, oder?

```
INFO successfully downloaded https://api.aerisapi.com/airquality/closest?p=52.152493,9.929383&format=json&radius=50mi&limit=1&client_id=5R5NlloB6lq0dsgnehmIg&client_secret=j9KaQEG8X2SUj1pHFAml7BvtggLWAQXq3mmkY33X
INFO write Belchertown JSON file to /etc/weewx/skins/Belchertown/dwd/forecast-openmeteo-52.152563-9.92929-icon_global-belchertown.json
INFO placemark id "openmeteo-52.152563-9.92929-icon_global" processed
INFO end loop over placemarks
```
Grüße!

**Comment by roe-dl** [comment]
Das Problem ist schon klar. Ich muß mir nur genau ansehen, daß ich mit einer Änderung keine Nebenwirkungen erzeuge. Dazu fehlte mir bis jetzt die Muße.

**Comment by teffi71** [comment]
> Dazu fehlte mir bis jetzt die Muße.

Das kann ich gut nachvollziehen :)

**Comment by roe-dl** [comment]
Nun, wie sieht es aus?

**Comment by teffi71** [comment]
Es sieht gut aus :)
`INFO download_aeris('aqi',(52.152472, 9.929346))`
und in `weewx.conf` steht `52.0` und `10.0`.
I am a happy camper ;)
Danke Dir!
