### ISSUE TITLE
Komische Fehlermeldung no such table: forecast_day_wind

### ISSUE THREAD

**Issue by olwaldi** [roe-dl/weewx-DWD#57]
Ich nutze ja seit Mitte Oktober 2023 das DWD forecast Modul auf meinem Raspberry pi3. Da ich gestern ein komisches Problem mit den GPIOs hatte, habe ich seit Langem mal wieder ins journalctl geguckt. Bzgl. GPIO gabs keine Fehlermeldungen, wohl aber bzgl. weewx-DWD. Die Fehler treten zeitabhängig auf, und zwar an JEDEM Tag immer exakt zwischen Mitternacht und 05:15 in 5min Abstand - unten nur ein Fehlerblock von journalctl als Beispiel

[Sorry - wieder cut&paste-Problem mit UNIX-ASCII ohne CR - aber immerhin lesbar]

`Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.imagegenerator.ImageGenerator'
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****  no such table: forecast_day_wind
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weedb/sqlite.py", line 39, in guarded_fn
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****      return fn(*args, **kwargs)
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weedb/sqlite.py", line 233, in execute
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****      return sqlite3.Cursor.execute(self, *args, **kwargs)
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****  sqlite3.OperationalError: no such table: forecast_day_wind
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****  During handling of the above exception, another exception occurred:
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****      obj.start()
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 385, in start
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****      self.run()
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/imagegenerator.py", line 44, in run
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****      self.gen_images(self.gen_ts)
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/imagegenerator.py", line 109, in gen_images
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****      plot = self.gen_plot(plotgen_ts,
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/imagegenerator.py", line 248, in gen_plot
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****      start_vec_t, stop_vec_t, data_vec_t = weewx.xtypes.get_series(
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 100, in get_series
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****      return xtype.get_series(obs_type, timespan, db_manager, aggregate_type,
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 920, in get_series
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****      return ArchiveTable.get_series(obs_type, timespan, db_manager, aggregate_type,
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 167, in get_series
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****      agg_vt = get_aggregate(obs_type, stamp, do_aggregate, db_manager)
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 127, in get_aggregate
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****      return xtype.get_aggregate(obs_type, timespan, aggregate_type, db_manager,
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 1102, in get_aggregate
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****      row = db_manager.getSql(sql, timespan)
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/manager.py", line 579, in getSql
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****      _cursor.execute(sql, sqlargs)
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weedb/sqlite.py", line 47, in guarded_fn
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****      raise weedb.NoTableError(e)
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****  weedb.NoTableError: no such table: forecast_day_wind
Nov 13 00:00:33 imurr9 python3[579]: weewx[579] ERROR weewx.reportengine:         ****  Generator terminated
`

Es sieht für mich so aus, als ob in der DWD forecast sqlite DB jeweils in dem Zeitraum die Tabelle forecast_day_wind fehlen würde, und nur die. Datenlücken habe ich aber trotzdem nicht, da ich mir die Wind-Vorhersagen nachts noch nie angeguckt habe. Tagsüber ist der Fehler weg, die Windvorhersagen sehen plausibel aus.

Das Ganze tritt seit Anfang November auf. journalctl-Einträge aus der Zeit davor habe ich leider nicht, da aufgrund eines kurzen Stromausfalls Anfang November mein Raspi abgestürzt ist, aber problemlos wieder gebootet hat. D.h. gut möglich, daß mein DWD-Problem irgendeine Datei beschädigt haben könnte. Aber warum funktioniert die DWD-Vorhersage vollkommen fehlerfrei zwischen 5:15 und Mitternacht??

Ratlos, Michael

**Comment by roe-dl** [comment]
Unter `[DataBindings]` unter `[[dwd_binding]]` muß beim Schlüssel `manager` ander als bei `[[wx_binding]]` der Wert `weewx.manager.Manager` stehen.

**Comment by olwaldi** [comment]
Am Montag, 13. November 2023, 11:49:50 CET schrieb roe-dl:
> Unter `[DataBindings]` unter `[[dwd_binding]]` muß beim Schlüssel `manager`
> ander als bei `[[wx_binding]]` der Wert `weewx.manager.Manager` stehen.
Danke für die prompte Antwort. Bei mir steht das allerdings bereits so
in /etc/weewx.conf (s.u., Kommentare entfernt). Und die Fehlermeldung tritt 
wirklich alle 5min nur zwischen 0:00 und 5:15 auf.

[DataBindings]
    [[wx_binding]]
        database = archive_sqlite
        table_name = archive
        manager = weewx.manager.DaySummaryManager
        schema = schemas.wview_extended.schema

    [[dwd_binding]]
        database = dwd_sqlite
        table_name = forecast
        manager = weewx.manager.Manager
        schema = schemas.dwd.schema

**Comment by roe-dl** [comment]
Da bin ich jetzt auch etwas überfragt. Mit `weewx.manager.Manager` sollte er Dateien der Art `forecast_day_*` nicht brauchen. Das wäre dann möglicherweise doch eher eine Frage für den allgemeinen WeeWX-Support. 

Die SQLITE-Datei mit der Vorhersage enthält nur eine einzige Tabelle. Sie hat den Namen `forecast`. 

Allerdings sehe ich hier noch etwas anderes. Eine Größe `wind` gibt es nämlich nicht. Es gibt nur `windSpeed`, `windDir`, `windGust` und ggf. `windGustDir`. Das trifft für die originale WeeWX-Tabelle ebenso wie für die DWD-Vorhersage zu.

**Comment by olwaldi** [comment]
Am Montag, 13. November 2023, 13:01:20 CET schrieb roe-dl:
> Da bin ich jetzt auch etwas überfragt. Mit `weewx.manager.Manager` sollte er
> Dateien der Art `forecast_day_*` nicht brauchen. Das wäre dann
> möglicherweise doch eher eine Frage für den allgemeinen WeeWX-Support.
> 
> Die SQLITE-Datei mit der Vorhersage enthält nur eine einzige Tabelle. Sie
> hat den Namen `forecast`.
> 
> Allerdings sehe ich hier noch etwas anderes. Eine Größe `wind` gibt es
> nämlich nicht. Es gibt nur `windSpeed`, `windDir`, `windGust` und ggf.
> `windGustDir`. Das trifft für die originale WeeWX-Tabelle ebenso wie für
> die DWD-Vorhersage zu.
Ich hab' mittleerweile zwei Ideen, woher das Problem kommen könnte.

1. Da ich ja die forecast-Daten im gleichen Graph wie die Meßdaten (eben 
rechts "hinter" dem letzten aktuellen Meßwert) ausgeben will, mußte ich 
irgendwie die x-Achse "verlängern" (bei aller Konfigurationsmöglichkeit von 
weewx geht das leider nicht standardmäßig). Dazu habe ich der Funktion 
scaletime() aus utilities.py den zusätzlichen Parameter offset verpaßt, um den 
zu zeichnenden Bereich über den letzten aktuellen x-Wert (Zeit) hin 
auszudehnen. Womöglich geht meine Berechnung schief, wenn ein Tageswechsel 
dazwischenliegt? Tagsüber funktioniert's prima.

2. Aus irgendeinem Grund werden die forecast-Daten vom DWD nachts fehlerhaft 
'runtergeladen. Dazu speichere ich heute Nacht mal die Datei von 3:00.

**Comment by roe-dl** [comment]
Nur noch mal zur Sicherheit die Nachfrage: Kann es sein, daß irgendwo `wind` statt `windSpeed` oder `windDir` verwendet wird?

**Comment by olwaldi** [comment]
Am Montag, 13. November 2023, 16:05:46 CET schrieb roe-dl:
> Nur noch mal zur Sicherheit die Nachfrage: Kann es sein, daß irgendwo `wind`
> statt `windSpeed` oder `windDir` verwendet wird?
Treffer, versenkt. Ja, ich mußte bei weekwinddir, monthwinddir und yearwinddir 
jeweils [[[[wind]]]] verwenden, da [[[[windDir]]]] anders als bei daywinddir 
NICHT funktioniert hat, z.B.

        [[[weekwinddir]]]
            yscale = 0.0, 360.0, 45.0
            line_type = None
            marker_type = box
            marker_size = 2
            [[[[wind]]]]
                aggregate_type = vecdir
            [[[[forecast_wind]]]]
                data_type = wind
                data_binding = dwd_binding
                aggregate_type = vecdir
                label = ' '
               color = blue

Darüberhinaus gibt's noch ein direktes "wind" in den plot_groups von meinem 
Seasons/skin.conf.

Nichtsdestotrotz verstehe ich nicht, warum die Fehlermeldungen täglich immer 
im gleichen Zeitfenster auftreten, ansonsten aber nicht. Die generierten plots 
sehen obendrein richtig aus.

**Comment by olwaldi** [comment]
Am Montag, 13. November 2023, 16:05:46 CET schrieb roe-dl:
> Nur noch mal zur Sicherheit die Nachfrage: Kann es sein, daß irgendwo `wind`
> statt `windSpeed` oder `windDir` verwendet wird?
Heute Nacht habe ich ein Kope fer forecast db gemacht - die ist voll OK.

Daher liegt der Fehler mit großer Wahrscheinlichkeit in meiner Änderung von 
utilities.py. Aber wie kann ich das testen?

Versucht habe ich
cd /usr/share/weewx/weeplot
python3 -i __init__.py

Aber dann fehlen viele includes. Auf welchen Werrt muß man PYTHONPATH setzen? 
Oder wie sollte man weewx Module anders testen?

**Comment by roe-dl** [comment]
Um die Frage trotzdem mal noch zu beantworten:

> Oder wie sollte man weewx Module anders testen?

Da gibt es das, was Tom Keffer immer als "instrumented" bezeichnet, also so viel wie möglich oder sinnvoll `loginf()`-Aufrufe in das problematische Modul einbauen und dann im Nachgang das Log auswerten. 

Ansonsten meine Frage: Ist jetzt bei diesem Issue noch etwas offen oder können wir das schließen?

**Comment by olwaldi** [comment]
Leider tritt der Fehler weiterhin auf trotz Ersetzen von wind durch windDir in skin.conf. Ich wäre auch sehr überrascht, wenn dadurch ein "Zeitproblem" gelöst werden könnte.

Wenn man die Fehlermeldungen genauer anguckt, kommt dort auch irgendwo ein timespan vor - hat also schon irgendwie mit meiner Code-Änderung zu tun. Die habe ich allerdings gestern relativ detailliert debuggt - ohne einen Fehler zu entdecken.

Neue Entdeckung: Die Zeitstempel in der forecast sdb scheinen ab ungefähr fünf Uhr keine Werte mehr vom Vortag zu enthalten, davor schon. Das würde zum Fehlerbild passen. Ob das ein Bug in weewx selber ist?

Heute Nacht sichere ich mal den HTML-Output. Mal sehen, welche Diagramme fehlen. Wenn mein Code Ursache ist, müßten ALLE Diagramme fehlen, da  alle denselben Zeitbereich benutzen.

**Comment by roe-dl** [comment]
Danke für das Update. 

Der Deutsche Wetterdienst liefert nur in größeren Abständen neue Vorhersagen. Jetzt um 10:45 Uhr ist die Vorhersage zum Beispiel von 04:00 Uhr. Davor stammen die Daten (auch in der *.sdb-Datei) vom Vortag.

**Comment by roe-dl** [comment]
* [Tom Keffer on Google Groups](https://groups.google.com/g/weewx-user/c/76qdbSy3bbQ/m/7BczZoENBwAJ)
* [changed xtypes.py](https://groups.google.com/group/weewx-user/attach/70d81663317ec/xtypes.py?part=0.1)
