### ISSUE TITLE
Fehlendes warnicon warn_icons_eis_pre.png

### ISSUE THREAD

**Issue by olwaldi** [roe-dl/weewx-DWD#58]
Eigentlich nicht Dein Problem - die *pre* Icons scheinen in "warnicons_nach_stufen_50x50_zip.zip" (File hat im Download wirklich den doppelten zip im Dateinamen) zu fehlen - ging  mir im Sommer mit gewitter_pre auch schon so.

Habe für mich einfach warn_icons_eis_3.png kopiert auf warn_icons_eis_pre.png

Grüßle aus dem verschneiten Süden, Michael

**Comment by roe-dl** [comment]
https://www.woellsdorf-wetter.de/dwd/warn_icons_50x50/warn_icons_eis_pre.png

**Comment by olwaldi** [comment]
Am Montag, 15. Januar 2024, 15:18:02 CET schrieb roe-dl:
> https://www.woellsdorf-wetter.de/dwd/warn_icons_50x50/warn_icons_eis_pre.png
Habe mir gleich alle verfügbaren *pre* geholt.

Danke, Michael
