### ISSUE TITLE
WeeWX v5 Kompatibilität

### ISSUE THREAD

**Issue by copain60** [roe-dl/weewx-DWD#59]
dwd-mosmix
dwd-warnings

Diese Module importieren 'configobj', was einen Fehler ergibt.

Ist die Erweiterung weewx-DWD mit WeeWX v5 kompatibel und lauffähig?

**Comment by roe-dl** [comment]
Aucht WeeWX 5 benutzt und importiert configobj. Daran kann das Problem also nicht liegen. Für weitere Hinweise bietet die Anfrage nicht genug Informationen.
