### ISSUE TITLE
Fehler: mosmix sqlite3 Datenbank wird nicht erstellt

### ISSUE THREAD

**Issue by copain60** [roe-dl/weewx-DWD#60]
- weewx 5.0.0
- Schema dwd.py Ordner: /home/RasPi Username/weewx-venv/bin, Attribut 664
- extensions.py Ordner: /home/RasPi Username/weewx-data/bin/user, Attribut 664
- Befehl: sudo /usr/local/bin/dwd-mosmix --config=/home/RasPi Username/weewx-data/weewx.conf --daily --hourly --json --database XXXXX

Fehlerlog:
Using configuration file /home/RasPi Username/weewx-data/weewx.conf
INFO successfully downloaded https://opendata.dwd.de/weather/local_forecasts/mos/MOSMIX_L/single_stations/XXXXX/kml/MOSMIX_L_LATEST_XXXXX.kmz
Traceback (most recent call last):
  File "/usr/local/bin/dwd-mosmix", line 2949, in <module>
    dwd.forecast_all(mmos,output,options.dry_run,lang=options.lang)
  File "/usr/local/bin/dwd-mosmix", line 2512, in forecast_all
    self.forecast_placemark(placemark, mos['ForecastTimeSteps'], issue, output, dryrun, lang)
  File "/usr/local/bin/dwd-mosmix", line 2483, in forecast_placemark
    self.write_database(placemark,timesteps,issue)
  File "/usr/local/bin/dwd-mosmix", line 2390, in write_database
    self.dbm_open(placemark['id'],columns)
  File "/usr/local/bin/dwd-mosmix", line 2543, in dbm_open
    self.connection = sqlite3.connect(fn)
                      ^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

Die Ergänzungen in dwd.py und extensions.py wurden gemäss Anleitung vorgenommen und XXXXX durch Mosmix ID ersetzt.

Wie kann ich die Datenbank 'dwd-forecast-XXXXX.sdb' erstellen?

**Comment by roe-dl** [comment]
> `sudo /usr/local/bin/dwd-mosmix --config=/home/RasPi Username/weewx-data/weewx.conf --daily --hourly --json --database XXXXX`

In dem Dateinamen ist ein Leerzeichen. Das ist regelmäßig eine Ursache für schwer zu findende Fehler. Daher wird empfohlen, auf Leerzeichen in Dateinamen grundsätzlich zu verzichten.

Sie können versuchen, den Pfad in Anführungszeichen einzuschließen:
```shell
sudo /usr/local/bin/dwd-mosmix --config="/home/RasPi Username/weewx-data/weewx.conf" --daily --hourly --json --database XXXXX
```

Und außerdem die Option `--verbose` hinzuzufügen, um ausführlichere Meldungen zu bekommen.

Sollte das nicht helfen, benötige ich zur weiteren Beurteilung den entsprechenden Ausschnitt aus `weewx.conf`.

**Comment by copain60** [comment]
- Der Username enthält kein Leerzeichen: 'RasPi Username' ist ein Platzhalter und wird durch den effektiven Namen ersetzt. Nehmen wir hier als User einfach 'RasPi'.
- Anführungszeichen und --verbose bringen keine Änderung. Die Fehler bleiben gleich.

Ausschnitte weewx.conf:
[DataBindings]
    [[forecast_binding]]
        database = forecast_sqlite
        table_name = archive
        manager = weewx.manager.Manager
        schema = user.forecast.schema

[Databases]
    [[dwd_sqlite]]
        database_name = dwd-forecast-XXXXX.sdb
        database_type = SQLite

[Engine]
[WeatherServices]
    path = '/home/RasPi/weewx-data/skins/Skinname/dwd'
    [[forecast]]
        icon_set = dwd
        icons = './dwd/icons'
        orientation = h, v
        show_obs_symbols = True    # optional
        show_obs_description = False    # optional
        show_placemark = True    # optional

'Skinname' als Platzhalter wird durch effektiven Namen ersetzt.

**Comment by copain60** [comment]
Im journalctl habe ich zusätzlich den Fehler ModuleNotFoundError: No module named 'schemas.dwd'

Nachdem ich dwd.py nach /home/RasPi/weewx-venv/lib/python3.11/site-packages/schemas mit Attribut 664 kopiert habe, scheint dieser verschwunden zu sein.

**Comment by roe-dl** [comment]
```
schema = user.forecast.schema
```

Diese Zeile besagt, daß es im Verzeichnis für die WeeWX-Erweiterungen namens `user` eine Datei `forecast.py` gibt in der wiederum ein Objekt namens `schema` definiert ist. 

Die Beschreibung besagt, daß die Datei `dwd.py` ins Verzeichnis `schemas` gespeichert werden soll und daß die Zeile `schema = schemas.dwd.schema` lauten soll. Das muß man nicht so machen, aber wenn es nicht funktioniert, empfiehlt es sich, erst einmal mit den vorgeschlagenen Orten zu beginnen.

Dann gibt es im Abschnitt `[DatabaseTypes]` im Unterabschnitt `[[SQLite]]` einen Schlüssel `SQLITE_ROOT`. Dieser muß auf ein beschreibbares Verzeichnis zeigen.

Und dann wäre die Frage, ob die Option `--verbose` außer derselben Fehlermeldung (was zu erwarten war) noch andere Ausgaben hervorgerufen hat, die ohne diese Option nicht kamen.

**Comment by copain60** [comment]
Im vorigen Post habe ich die Ausschnitte der weewx.conf ergänzt.

dwd.py liegt nun im Ordner /home/RasPi/weewx-venv/lib/python3.11/site-packages/schemas mit Attribut 664.

weewx v5 gibt den Pfad von SQLITE_ROOT standardmässig wie folgt vor:
[DatabaseTypes]
    # Defaults for SQLite databases.
    [[SQLite]]
        driver = weedb.sqlite
        # Directory in which database files are located, relative to WEEWX_ROOT
        SQLITE_ROOT = archive

Nachdem ich den Pfad gemäss weewx v4.10 änderte, ergab --verbose folgenden Fehler:
Pfad v4.10: SQLITE_ROOT = %(WEEWX_ROOT)s/archive
Fehler:
Traceback (most recent call last):
  File "/usr/local/bin/dwd-mosmix", line 2907, in <module>
    dwd = DwdMosmix(config,options.verbose)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/dwd-mosmix", line 628, in __init__
    self.SQLITE_ROOT = config_dict['DatabaseTypes']['SQLite']['SQLITE_ROOT']
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/configobj/__init__.py", line 557, in __getitem__
    return self._interpolate(key, val)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/configobj/__init__.py", line 549, in _interpolate
    return engine.interpolate(key, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/configobj/__init__.py", line 352, in interpolate
    value = recursive_interpolate(key, value, self.section, {})
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/configobj/__init__.py", line 330, in recursive_interpolate
    k, v, s = self._parse_match(match)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/configobj/__init__.py", line 417, in _parse_match
    value, section = self._fetch(key)
                     ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/configobj/__init__.py", line 386, in _fetch
    raise MissingInterpolationOption(key)
configobj.MissingInterpolationOption: missing option "WEEWX_ROOT" in interpolation.

**Comment by copain60** [comment]
Die Fehler deuten auf einen Ursprung in dwd-mosmix hin.

Falls der sqlite_root Pfad die Ursache ist, würde das bedeuten, dass die geänderte Standardeinstellung in weewx v5 (gegenüber weewx v4.10) in dwd-mosmix nachvollzogen werden müsste, damit mosmix auch mit weewx v5 Standardeinstellungen lauffähig ist.

Sehen Sie das auch so?
Haben Sie die Kompatibilität von mosmix mit weewx v5 Standards schon bei Ihnen erfolgreich getestet?

**Comment by copain60** [comment]
Mit dem Pfad
SQLITE_ROOT = /home/RasPi/weewx-data/archive
wird die Datenbank erstellt!

Ich werde weewx-DWD / dwd-mosmix auf Updates verfolgen.

**Comment by roe-dl** [comment]
See commit 4488e24

> Haben Sie die Kompatibilität von mosmix mit weewx v5 Standards schon bei Ihnen erfolgreich getestet?

Ich habe WeeWX 5 in der DEB-Paket-Variante getestet. Möglicherweise steht dort bei SQLITE_ROOT ein absoluter Pfad.

**Comment by copain60** [comment]
- SQLITE_ROOT = archive
- dwd-mosmix ausgetauscht
- Datenbank 'dwd-forecast-XXXXX.sdb' gelöscht
- Befehl: sudo /usr/local/bin/dwd-mosmix --config=/home/RasPi/weewx-data/weewx.conf --daily --hourly --json --database XXXXX

Nach Ausführung erscheint folgende Info:
Using configuration file /home/RasPi/weewx-data/weewx.conf
INFO successfully downloaded https://opendata.dwd.de/weather/local_forecasts/mos/MOSMIX_L/single_stations/XXXXX/kml/MOSMIX_L_LATEST_XXXXX.kmz

Die Option --verbose zeigt am Schluss:
INFO json
INFO database
INFO placemark id "XXXXX" processed
INFO end loop over placemarks

Die Datenbank wird nicht erstellt!
Es erscheint keine weitere Fehlermeldung.

Sind Sie sicher, dass der Pfad korrekt ist?

**Comment by roe-dl** [comment]
Mit `--verbose` zeigt er doch am Anfang die Konfigurationsdaten. Da wird auch ausgegeben, was er als SQLITE_ROOT erkannt hat. Was wird da ausgegeben?

**Comment by copain60** [comment]
- geändertes mosmix
- weewx.conf SQLITE_ROOT = archive (Standard weewx v5)
- verbose:
-- configuration data ----------------------------------
log success:       True
log failure:       True
target path:       /home/RasPi/weewx-data/skins/Skinname/dwd
horiz. tab:        True
vertical tab:      True
icon set:          5
station location:  lat XXX lon XXX alt XXX
aeris api id:      None
aeris api secret:  None
SQLITE_ROOT:       None
- Datenbank wird NICHT erstellt!

Mit dem vorherigen mosmix und weewx.conf SQLITE_ROOT = /home/RasPi/weewx-data/archive ist verbose identisch, ausser:
SQLITE_ROOT:       /home/RasPi/weewx-data/archive
Wie erwähnt, wird mit dieser Konfiguration die Datenbank erstellt.

**Comment by roe-dl** [comment]
> `SQLITE_ROOT: None`

Ok, das ist das Problem. Ich versuche, herauszufinden, warum das so ist.

Was enthält `WEEWX_ROOT`?

**Comment by copain60** [comment]
Mit welchem Befehl finde ich das auf dem RasPi heraus?

**Comment by roe-dl** [comment]
> Mit welchem Befehl finde ich das auf dem RasPi heraus?

Hier geht es um den Inhalt von `weewx.conf`. 

Es ist immer schwierig, Probleme zu lösen, wenn man nur einen Teil der Information hat. Deswegen empfiehlt Tom Keffer in den Regeln zu Anfragen, die Ausgabe von `weectl debug` - nach Prüfung, daß keine Paßwörter mehr enthalten sind - in die Anfrage aufzunehmen. Nicht immer braucht man alles, was da drinsteht. Aber dem Angefragten liefert es zuweilen Informationen, die man als Anfragender nicht vermutet. Im vorliegenden Fall kenne ich nur Ausschnitte aus `weewx.conf`. Wir wissen, daß der Schlüssel `WEEWX_SQLITE` einen relativen Pfad enthält, nämlich `archive`. Um den kompletten, absoluten Pfad zu bekommen, müssen weitere Schlüssel aus `weewx.conf` ausgewertet werden. Zu diesen gehört `WEEWX_ROOT`, der ziemlich am Anfang von `weewx.conf` stehen muß.

**Comment by copain60** [comment]
WEEWX_ROOT = /home/RasPi/weewx-data

**Comment by roe-dl** [comment]
Hm.

Wenn ich eine Konfigurationsdatei erzeuge, die enthält:
```
WEEWX_ROOT = /home/RasPi/weewx-data
[DatabaseTypes]
    [[SQLite]]
        SQLITE_ROOT = archive
```

dann zeigt er bei mir beim Aufruf von `dwd-mosmix --verbose` an:
```
SQLITE_ROOT:       /home/RasPi/weewx-data/archive
```

Kann es sein, daß das Wort, das anstelle von `RasPi` wirklich steht, irgendwelche Besonderheiten aufweist? Sonderzeichen? Leerzeichen? Interpunktionszeichen, speziell Kommata?

Hilft es eventuell, den Pfad bei `WEEWX_ROOT` in Anführungszeichen einzuschließen?

**Comment by copain60** [comment]
Wenn Sie sich weewx.conf in weewx-5.0.1.tgz anschauen, stellen Sie fest, dass WEEWX_ROOT darin NICHT definiert ist.
Ich habe die Variable aus weectl debug herausgelesen, deshalb meine Frage nach dem Befehl.

**Comment by roe-dl** [comment]
a) Kommt `WEEWX_ROOT` in Ihrer `weewx.conf`vor? Bitte mit einem Editor öffnen und nachschauen.
b) Darf ich denn die komplette Ausgabe von `weectl debug` sehen? Vielleicht fällt mir dann etwas ein.

**Comment by copain60** [comment]
NEIN

**Comment by roe-dl** [comment]
Das weiß ich. Trotzdem wird der Schlüssel `WEEWX_ROOT` innerhalb des Programms genutzt. Also muß es ihn geben. Ich habe zwischenzeitlich auch einen Kommentar dazu gefunden, und zwar in `weecfg/__init__.py`:
```
    Special handling for key "WEEWX_ROOT":
        - If it is missing from the config file, then it is added and set to the directory
        where the configuration file was found.
        - If it is a relative path, then it is converted to an absolute path by
        prepending the directory where the configuration file was found.
```

Dann versuchen wir das mal nachzuempfinden.

**Comment by copain60** [comment]
- weewx.conf: SQLITE_ROOT = archive
- weewx.conf: OHNE Variable WEEWX_ROOT

Mit dem neuen mosmix wird mit weewx v5.0.0 die Datenbank erstellt.

Besten Dank für das Update.
