### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by holifo** [roe-dl/weewx-DWD#61]
sudo weectl extension install master.zip
Using configuration file /etc/weewx/weewx.conf
Install extension 'master.zip' (y/n)? y
Extracting from zip archive master.zip
Traceback (most recent call last):
  File "/usr/share/weewx/weectl.py", line 74, in <module>
    main()
  File "/usr/share/weewx/weectl.py", line 66, in main
    namespace.func(namespace)
  File "/usr/share/weewx/weectllib/__init__.py", line 121, in dispatch
    namespace.action_func(config_dict, namespace)
  File "/usr/share/weewx/weectllib/extension_cmd.py", line 116, in install_extension
    ext.install_extension(namespace.source, no_confirm=namespace.yes)
  File "/usr/share/weewx/weecfg/extension.py", line 138, in install_extension
    extension_name = self._install_from_file(extension_path, filetype)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/weewx/weecfg/extension.py", line 168, in _install_from_file
    extension_name = self.install_from_dir(extension_dir)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/weewx/weecfg/extension.py", line 179, in install_from_dir
    installer_path, installer = weecfg.get_extension_installer(extension_dir)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/weewx/weecfg/__init__.py", line 714, in get_extension_installer
    __import__('install')
  File "/tmp/tmp17882ax5/weewx-DWD-master/install.py", line 67
    }
    ^
SyntaxError: closing parenthesis '}' does not match opening parenthesis '(' on line 29

**Comment by roe-dl** [comment]
Did that small fix help?

**Comment by GameWatchProjects** [comment]
Hello,

same error here as the thread starter:

> Using configuration file /etc/weewx/weewx.conf
> Install extension 'weewx-dwd.zip' (y/n)? y
> Extracting from zip archive weewx-dwd.zip
> Traceback (most recent call last):
>   File "/usr/share/weewx/weectl.py", line 74, in <module>
>     main()
>   File "/usr/share/weewx/weectl.py", line 66, in main
>     namespace.func(namespace)
>   File "/usr/share/weewx/weectllib/__init__.py", line 121, in dispatch
>     namespace.action_func(config_dict, namespace)
>   File "/usr/share/weewx/weectllib/extension_cmd.py", line 116, in install_extension
>     ext.install_extension(namespace.source, no_confirm=namespace.yes)
>   File "/usr/share/weewx/weecfg/extension.py", line 138, in install_extension
>     extension_name = self._install_from_file(extension_path, filetype)
>   File "/usr/share/weewx/weecfg/extension.py", line 168, in _install_from_file
>     extension_name = self.install_from_dir(extension_dir)
>   File "/usr/share/weewx/weecfg/extension.py", line 179, in install_from_dir
>     installer_path, installer = weecfg.get_extension_installer(extension_dir)
>   File "/usr/share/weewx/weecfg/__init__.py", line 714, in get_extension_installer
>     __import__('install')
>   File "/tmp/tmpznzh4jcw/weewx-DWD-master/install.py", line 36
>     config={
>     ^
> SyntaxError: expression cannot contain assignment, perhaps you meant "=="?

**Comment by roe-dl** [comment]
I hope this fix covers all the remaining bugs.

**Comment by GameWatchProjects** [comment]
@roe-dl 
ok, ich denke das ich hier in deutscher Sprache schreiben kann ...

erst einmal danke für die Zeit, die Du investierst um uns dieses Plugin zu ermöglichen.

Nun habe ich mir mal das neue Update des Plugin's herunter geladen und erhalte diese Ausgabe bei der Installation, was sich von anderen Plugins bisher in der Ausgabe erheblichst unterscheidet:

> Using configuration file /etc/weewx/weewx.conf
> Install extension 'weewx-dwd.zip' (y/n)? y
> Extracting from zip archive weewx-dwd.zip
> {'WEEWX_ROOT': '/etc/weewx', 'USER_DIR': '/etc/weewx/bin/user', 'BIN_DIR': '/usr/share/weewx', 'EXT_DIR': '/etc/weewx/bin/user/installer', 'SKIN_DIR': '/etc/weewx/skins'}
> chmod u=rwx,g=rx,o=rx /etc/weewx/bin/user/capwarnings.py
> ln -s /etc/weewx/bin/user/capwarnings.py /usr/local/bin/dwd-cap-warnings
> ln -s /etc/weewx/bin/user/capwarnings.py /usr/local/bin/bbk-warnings
> ln -s /etc/weewx/bin/user/capwarnings.py /usr/local/bin/msc-warnings
> cp /etc/weewx/bin/user/usr/local/bin/wget-dwd /usr/local/bin/wget-dwd
> chmod u=rwx,g=rx,o=rx /usr/local/bin/wget-dwd
> cp /etc/weewx/bin/user/usr/local/bin/html2ent.ansi /usr/local/bin/html2ent.ansi
> chmod u=rwx,g=rx,o=rx /usr/local/bin/html2ent.ansi
> Saving installer file to /etc/weewx/bin/user/installer/weather forecasts
> Saved copy of configuration as /etc/weewx/weewx.conf.20240229004717
> Finished installing extension weather forecasts from weewx-dwd.zip

Auch taucht das Plugin nicht in der Übersicht der installierten Plugins auf mit
`$ sudo weectl extension list`

Wie man es deinstallieren kann, wenn es in der Liste nicht auftaucht, ist mir aktuell schleierhaft, hier kann man anscheinend nur manuell eingreifen, wobei der Aufwand vermutlich nicht gerechtfertigt ist, da man nun nicht weiß, wo es sicher während der Installion überall verewigt hat. Wohl dem, der regelmäßige Backup's anlegt.

In meinem Fall halb so wild, da BAckup regelmäßig erstellt werden und ich neue Plugins erst unmittelbar nach einem erfolgeichen Backup teste, dann verliert man nicht so viele Daten. Werde das letzte Backup daher wieder zurück spielen, geht schneller, als hier nach Datenmüll zu suchen.

Vorschlag, bitte einmal Updates als STABLE oder BETA kennzeicnen, dann können sich die Leute vieleicht vorher überlegen, ob sie es sich installieren. Habe jetzt drei mal getestet und bin dreimal auf die Nase gefallen, daher verzichte ich dankend künftig auf das Plugin, was jetzt nicht undankbar sein soll, aber es ist für die Weewx Version 5.0 einfach noch nicht ausgereift, zumindest in meinem Falle nicht.

**Comment by roe-dl** [comment]
Die Ausgabe ist erst einmal in Ordnung. Diese Erweiterung benötigt einige Links, die dort erzeugt werden, was offenbar erfolgreich war. 

Warum die Erweiterung nicht in der Liste der Erweiterungen auftaucht, entzieht sich meiner Kenntnis. Die Funktionen, die die Installationen ausführen, liegen im Kern von WeeWX. Darauf habe ich keinen Einfluß.

Erweiterungen unter WeeWX sind relativ einfach. Alle Dateien werden ins `user`-Verzeichnis kopiert. Vor den Änderungen an der Konfiguration wird automatisch ein Backup der Konfigurationsdatei `weewx.conf` angelegt, was der Ausgabe von der Installation auch zu entnehmen ist: `Saved copy of configuration as /etc/weewx/weewx.conf.20240229004717`. Es genügt regelmäßig, die Änderungen in `weewx.conf` rückgängig zu machen, wenn man eine Erweiterung wieder loswerden will.

Ursprünglich wollte ich diese Funktionen auch gar nicht veröffentlichen. Deswegen ist das so eine Sammlung ohne Versionsnummer und alles. Die Leute haben mich gebeten, es trotzdem zu tun. Bisher hat sich niemand daran gestört, daß die Installation etwas holprig ist.

**Comment by roe-dl** [comment]
> Auch taucht das Plugin nicht in der Übersicht der installierten Plugins auf mit
> `$ sudo weectl extension list`

Bei mir zeigt es die Erweiterung bei diesem Auftruf mit an. Ich habe trotzdem vorsichtshalber mal noch das Leerzeichen entfernt.

Und mit sudo `weectl extension uninstall 'weather forecasts'` wurde die Erweiterung auch korrekt deinstalliert. 

Ich kann die Kritik also nicht nachvollziehen.

Zu bemerken wäre noch, daß diese Erweiterung erhöhten Konfigurationsaufwand beeinhaltet. Man muß Informationen zu den Orten, für die man Daten, Warnungen und/oder Vorhersagen haben möchte, in die Konfiguration eintragen. Wie ein Ort zu spezifizieren ist, ist vom Anbieter abhängig, den man mittels dieser Erweiterung abfragen möchte. Bei den Landkarten muß darüber hinaus der Kartenausschnitt definiert werden, der erzeugt werden soll. Bloßes Installieren ist es also nicht. Das [Wiki](https://github.com/roe-dl/weewx-DWD/wiki) gibt hier zusätzliche Hinweise. Für Leute, die neu mit WeeWX beginnen, ist es sicherlich zu empfehlen, diese Erweiterung ans Ende zu setzen und erst einmal Erfahrungen mit WeeWX selbst und der Konfiguration von Skins zu sammeln.

**Comment by roe-dl** [comment]
Nachdem jetzt eine Woche kein weiterer Beitrag gekommen ist, mache ich dieses Issue zu.
As there were no further posts for one week now, I will close this issue.
