### ISSUE TITLE
Install Errors

### ISSUE THREAD

**Issue by GameWatchProjects** [roe-dl/weewx-DWD#62]
You have closed my last report, while you have "fixed" the error, but here is the new error:

> Using configuration file /etc/weewx/weewx.conf
> Install extension 'weewx-dwd.zip' (y/n)? y
> Extracting from zip archive weewx-dwd.zip
> Traceback (most recent call last):
>   File "/usr/share/weewx/weectl.py", line 74, in <module>
>     main()
>   File "/usr/share/weewx/weectl.py", line 66, in main
>     namespace.func(namespace)
>   File "/usr/share/weewx/weectllib/__init__.py", line 121, in dispatch
>     namespace.action_func(config_dict, namespace)
>   File "/usr/share/weewx/weectllib/extension_cmd.py", line 116, in install_extension
>     ext.install_extension(namespace.source, no_confirm=namespace.yes)
>   File "/usr/share/weewx/weecfg/extension.py", line 138, in install_extension
>     extension_name = self._install_from_file(extension_path, filetype)
>   File "/usr/share/weewx/weecfg/extension.py", line 168, in _install_from_file
>     extension_name = self.install_from_dir(extension_dir)
>   File "/usr/share/weewx/weecfg/extension.py", line 212, in install_from_dir
>     save_config |= installer.configure(self)
>   File "/tmp/tmp5kts_gke/weewx-DWD-master/install.py", line 83, in configure
> KeyError: 'USER_ROOT'

**Comment by roe-dl** [comment]
Sorry. I re-opened it.

**Comment by roe-dl** [comment]
See #61. Sorry again for closing the other issue. It was some automation of Github I did not consider.
