### ISSUE TITLE
Installationsdirectory unklar

### ISSUE THREAD

**Issue by olwaldi** [roe-dl/weewx-DWD#64]
Habe gerade entdeckt, daß es eine Reihe neuer Features in weewx-DWD gibt. Leider ist mir unklar, wohin die Python-Skripte installiert werden sollen. Wenn ich weewx-5.0 richtig verstanden habe, liegen die User-Erweiterungen unter /etc/weewx/bin/user und nicht mehr unter /usr/share/weewx/user (letztere Directory gibts auch nicht mehr). Daher habe ich z.B. weatherservicesradar.py nach /etc/weewx/bin/user kopiert. Rufe ich dieses Skript direkt manuell auf, gibts die Fehlermeldung
 `python3 ./weatherservicesradar.py --help
Traceback (most recent call last):
  File "/etc/weewx/bin/user/./weatherservicesradar.py", line 130, in <module>
    from user.weatherservicesutil import wget, BaseThread
ModuleNotFoundError: No module named 'user'`

Im src findet sich die Zeile
`sys.path.append('/usr/share/weewx')`
die auf die weewx-Installation an sich verweist. Wenn ich hier /etc/weewx/bin (bewußt ohne user) eintrage, wird (logischerweise) weewx nicht gefunden.

Wohin sollen user-Erweiterungen ab weewx-5.0 installiert werden?

Als workaround habe ich /usr/shared/weewx/user als symbolic link verfügbar gemacht.

**Comment by roe-dl** [comment]
Ganz grundsätzlich sollte die Installation mit `weectl extension install` inzwischen funktionieren. Die Dateien werden dabei nach `/etc/weewx/bin/user` kopiert. Es werden in jedem Fall alle Dateien benötigt, die in den Quellen unter `bin/user` liegen.  

Der Direktaufruf von `weatherservicesradar.py` ist eigentlich nur für Testzwecke gedacht. Der Aufrufpfad muß sowohl das Grundverzeichnis von WeeWX (`/usr/share/weewx` bei Packetinstallation, irgendwo unterhalb des Benutzerverzeichnisses bei `pip`-Installation) als auch das übergeordnete Verzeichnis des `user`-Verzeichnisses enthalten. Für den normalen Gebrauch als Dienst innerhalb von WeeWX spielt das aber keine Rolle, weil WeeWX die Pfade korrekt einstellt. Für den direkten Aufruf könnte man `sys.path.append` zweimal aufrufen, einmal mit dem WeeWX-Verzeichnis und einmal mit `sys.path.append('/etc/weewx/bin'`. Oder man macht eben einen symbolischen Link wie beschrieben. Ich werde nochmal versuchen, die Importe auf relative Pfade umzustellen.

Es gibt nur noch zwei Dateien, die regulär direkt aufgerufen werden müssen. Das sind `dwd-mosmix` und `capwarnings.py`. Für letzteres sind drei symbolische Links unter verschiedenen Namen nach `/usr/local/bin` anzulegen. `dwd-mosmix` kann direkt nach `/usr/local/bin` kopiert werden. Automatisch werden diese Links nur bei der Paketinstallation angelegt. Bei der `pip`-Installation, die nicht als `root` erfolgt, ist das nicht möglich. Da muß man das nachträglich mit der Hand machen. 

`wget-dwd` wird nicht mehr benötigt. Es wird vollständig durch den Abschnitt `[[download]]` unter `[WeatherServices]` ersetzt, wodurch sich der Funktionsumfang sogar noch erweitert hat.

**Comment by roe-dl** [comment]
Können wir dieses Issue schließen oder gibt es hier noch offene Fragen?

**Comment by olwaldi** [comment]
Kann geschlossen werden.
