### ISSUE TITLE
Unschöner Leerraum in Text-Vorhersagen

### ISSUE THREAD

**Issue by olwaldi** [roe-dl/weewx-DWD#65]
Eigentlich kein neues Problem, konnte ich aber bislang in wget_dwd selber mit sed-Pattern fixen. Jetzt erfolgt der Download (praktischerweise) direkt durch dwd-mosmix, und dann habe ich dieses Leerraumproblem wieder zurück:

Wenn ich die textuelle Wettervorhersage mittels
#include raw "dwd/VHDL50_DWSG_LATEST.html"
(oder auch ohne raw) einbinde, werden die Leerräume aus dem HTML-File (richtigerweise) mitgerendert. Die HTML-Datei beginnt aber z.B. mit einer Leerzeile und hat rund um die Überschrift im \<strong> weitere Leerzeilen, so daß der Text unschön nach unten rutscht
`Leerzeile

\<strong>

Nachts im Norden ...

\</strong>

Leerzeile

Text

Leerzeile`

Auch das Visualisieren hier ist mühsam, da der Markdown (bei mir?) Code nicht umbricht, solange ich nur ein Linefeed benutze - das ist aber ein Github-Problem.

Hier im Screenshot sieht man die unschönen Leerzeilen:
![grafik](https://github.com/user-attachments/assets/a7e62215-63f8-4d35-a709-3d87d085042e)

Hauptursache wird sein, daß die Datei eine DOS-Datei mit aus Linux-Sicht falschem CR/LF ist. iconv/recode lösen leider nicht das Leerzeilen-Problem.

Was tun?

**Comment by roe-dl** [comment]
Bei mir macht er die Leerzeilen in der Anzeige nicht, z.B. [Vorhersage Döbeln](https://www.woellsdorf-wetter.de/forecast/doebeln.html). Und wenn man die Webseite herunterlädt und im Texteditor ansieht (oder in den Entwicklertools des Browsers), dann sieht man, daß die Leerzeilen alle noch drin sind.

**Comment by olwaldi** [comment]
Der (unerwünschte) Leerraum wird durch meinen \<div  style="white-space: pre-line;"> Eintrag verursacht. Nehme ich ein \<p>, ist der weg. Habe ich vor gut einem Jahr aber absichtlich so gemacht, um die \<strong> Überschrift in einer separaten Zeile auszugeben.

Aber dann nehme ich eben doch das \<p> und Alles ist gut.

**Comment by roe-dl** [comment]
Es gibt auch noch `<br />`, um einen Zeilenumbruch einzufügen.

**Comment by olwaldi** [comment]
Im Prinzip ja, aber nicht so ohne Weiteres in der vom DWD (automatisch) erzeugten HTML-Datei - da steht das \<strong> ja vorne drin.

**Comment by roe-dl** [comment]
Man müßte das `<br />` nach dem `</strong>` einfügen. Während man einen Absatz in `<p>` und `</p>` einschließt, steht `<br />` für sich.

**Comment by olwaldi** [comment]
Ja, klar. Aber das \<strong> steht in der vom DWD generierten Datei VHDL50_DWSG_LATEST.html  selber drin. In meiner alten Lösung habe ich diese Datei vor der Verarbeitung per sed manipuliert, was ja jetzt nicht mehr geht.

Ist aber wirklich kein Beinbruch:-)

**Comment by roe-dl** [comment]
Ich habe mal etwas eingebaut. Bitte die Option `insert_lf_after_summary = true` testen.

**Comment by olwaldi** [comment]
Funktioniert prima bei mir - Danke für diese Spezialoption:
![grafik](https://github.com/user-attachments/assets/e94fe56c-5841-49c6-907e-2b408ea86960)

**Comment by roe-dl** [comment]
Bitte sehr!
