### ISSUE TITLE
Keine Ausgabe von Pollen für area 110 (Baden-Württemberg)

### ISSUE THREAD

**Issue by olwaldi** [roe-dl/weewx-DWD#66]
Hoffentlich sitzt der Fehler nicht wieder vor dem Bildschirm:-) - aber ich kriege keine Pollen-Daten. Im weewx.conf steht (aber richtig eingerückt):

```
 [WeatherServices]
    path = /etc/weewx/skins/Seasons_DWD/dwd
    [[download]]
        [[[Schilder]]]
            provider = DWD
            model = warning-map-with-symbols
            area = SU
    [[forecast]]
        icons = icons/wetter
        icon_set = dwd
        orientation = h
        [[[K2714]]]
            provider = DWD
	    model = MOSMIX
        [[[Baden-Württemberg]]]
            provider = DWD
            model = text
	    area = DWSG
	[[[Health]]]
            provider = DWD
            model = biowetter
	    area = 'I'
	    file = 'I'
	    prefix = ''
	[[[Pollen]]]
            provider = DWD
            model = pollen
	    area = 110
	    file ='110'
	    prefix = ''
```
Habe auch mal versucht, area als String mit quotes anzugeben - ohne Erfolg. Es wird keine Datei in der Subdirectory dwd/health-pollen-110.inc erzeugt.

Wenn ich im Skin
 \<p class="widget_forecast">Pollen von $current.pollenIssued.\</p>
ausgebe, gibts eine passende Fehlermeldung im HTML
Pollen von ?'pollenIssued'?.

biowetter hingegen funktioniert mit den analogen Einstellungen problemlos - da wird der passende Zeitstempel ausgegeben, und die erwartete Datei im Ordner dwd angelegt [abenr mit dem Layout der erzeugten biowetter-Tabelle muß ich noch was experimentieren].

**Comment by roe-dl** [comment]
Für eine ordentliche Einrückung drei Backticks vor und drei Backticks nach dem Konfigurationsausschnitt.

Ich bin mir nicht sicher, aber möglicherweise müssen Hochkommata um die Zahl: `area = '110'`.

**Comment by olwaldi** [comment]
Mit der area=112 tut's prima!
