### ISSUE TITLE
DWD Vorhersage wird nicht auf Mobiltelefon dargestellt

### ISSUE THREAD

**Issue by teffi71** [roe-dl/weewx-DWD#68]
Ich erhalte die Wettervorhersage über mosmix von DWD und Open-Meteo.
Im Webbrowser am PC wird die Tabelle entsprechend dargestellt.

<img width="1225" alt="Screenshot 2024-08-02 at 18 17 13" src="https://github.com/user-attachments/assets/492040cb-7eb3-4fcb-99ed-5d144cb70d2f">

Auf dem iPhone (egal ob mit Safari oder FireFox) wird die Tabelle nicht dargestellt ![IMG_6857](https://github.com/user-attachments/assets/3a1543e4-85e3-43f9-9a6c-4b472bf9630b) obwohl die Orientierung für beide Richtungen (h, v) angegeben ist.

`[WeatherServices]
    path = /etc/weewx/skins/Belchertown/dwd
    [[current]]
        safe = True
    [[forecast]]
        icons = ../images
        orientation = h, v
`

Was mache ich falsch? Oder habe ich etwas missverstanden?

**Comment by roe-dl** [comment]
Die Sichtbarkeit wird von den Klassen `hidden-xs` und `visible-xs-block` gesteuert. Diese Klassen müssen wie folgt definiert sein:

```
.visible-xs-block {
    display:none !important;
}
@media (max-width:767px) {
    .hidden-xs {
        display:none !important;
    }
    .visible-xs-block {
        display:block !important
    }
}
```

Es wäre zu prüfen, ob sie vorhanden sind. In `bootstrap.min.css` sind sie enthalten. Bei anderen Frameworks müssen sie eventuell ergänzt werden. Und falls mehrere CSS-Dateien eingebunden sind, dürfen sie in einer späteren Datei nicht wieder aufgehoben werden. Man muß also alle eingebundenen `*.css`-Dateien danach durchsuchen. Bei solchen, die auf `*.min.css` enden, ist das nicht so einfach, weil alles in einer einzigen Zeile steht. Aber es hilft nichts.

Man kann das prüfen, indem man mit der rechten (!) Maustaste auf den Beginn der Tabelle klickt und im Kontext-Menü "Element-Information" (Safari) oder "Untersuchen" (Firefox) anklickt. Links sieht man den HTML-Text und kann die Zeile anklicken, die `hidden-xs` bzw. `visible-xs-block` enthält. In der Mitte werden dazu die aktiven Klassen angezeigt. Dann kann man das Browserfenster zusammenschieben, daß es ganz schmal wird. Während es anfangs nur die Klasse `visible-xs-block` gibt, kommt beim Zusammenschieben irgendwann `hidden-xs` dazu, wenn es richtig läuft.

**Comment by teffi71** [comment]
Wenn das Fenster noch breit genug ist, wird die Tabelle angezeigt [DWD Forecast](http://weather.stegli.de/forecast/) ...
<img width="2471" alt="Screenshot 2024-08-03 at 16 10 57" src="https://github.com/user-attachments/assets/17357980-f039-4c34-ac5c-bef02bd6ef3b">

Wenn ich das Fenster schmaler mache, verschwindet die Tabelle ...
ich sehe etwas von `.hidden-xs` aber nichts von `.visible-xs-block`:
<img width="2469" alt="Screenshot 2024-08-03 at 16 10 31" src="https://github.com/user-attachments/assets/aeef28b6-e1ce-4056-95d8-a7c1d1526cea">

<img width="1765" alt="Screenshot 2024-08-03 at 16 12 17" src="https://github.com/user-attachments/assets/87724143-3480-4424-a880-3723d9da4ef3">

Hilft dies Dir weiter?

**Comment by teffi71** [comment]
Hier der `.visible-xs-block`:

<img width="2496" alt="Screenshot 2024-08-03 at 16 26 11" src="https://github.com/user-attachments/assets/f333941b-b358-476a-86b5-3ac0915970a8">

**Comment by roe-dl** [comment]
Einige Zeilen tiefer als das `<div ...hidden-xs` steht eine Zeile mit `<div ... visible-xs-block`. Bitte die mal auswählen und gucken, was da daneben angezeigt wird.

**Comment by teffi71** [comment]
Here we go ...
<img width="2480" alt="Screenshot 2024-08-04 at 12 52 40" src="https://github.com/user-attachments/assets/b204cfae-314c-4c25-ade0-8dd739d60663">

**Comment by roe-dl** [comment]
Aha. Also liegt das Übel in `belchertown-dark.min.css`. Diese Datei definiert alle möglichen Klassen aus dem Bootstrap-Framework neu und treibt dabei einigen Unfug. 

Als Gegenprüfung wäre es sinnvoll zu sehen, ob das Problem auch bei hellem Hintergrund auftritt.

Wenn sich ergibt, daß das Problem auf dunklen Hintergrund beschränkt ist, geht an einer Aufräumaktion in `belchertown-dark.min.css` kein Weg vorbei. Ich selbst habe das auch tun müssen. Das Ergebnis [belchertown-dark.css.zip](https://github.com/user-attachments/files/16487390/belchertown-dark.css.zip) muß aber nicht funktionieren, weil es Teil einer größeren Aufräumaktion war, die auch die Template-Dateien einschloß.

**Comment by teffi71** [comment]
Danke für Deine bisherige Hilfe!

Es liegt wohl tatsächlich an `belchertown-dank.min.css`, da mit dem hellen Hintergrund die Vorhersage erscheint ;)

<img width="2506" alt="Screenshot 2024-08-04 at 15 49 31" src="https://github.com/user-attachments/assets/4dc5788f-d4e7-41bd-a984-5df86327ed10">

Ich werde mir jetzt mal Dein Zip anschauen und hoffentlich entsprechend fortschreiten können :)

**Comment by teffi71** [comment]
Hab herzlichen Dank!
Jetzt läuft es, wie es soll!


<img width="2545" alt="Screenshot 2024-08-04 at 17 34 36" src="https://github.com/user-attachments/assets/0885de69-0044-4715-92c2-1ab7c5e3ac69">

**Comment by teffi71** [comment]
Closed as solved!
