### ISSUE TITLE
Nach reboot funktioniert cheetahgenerator bei bio Wetter nicht mehr

### ISSUE THREAD

**Issue by olwaldi** [roe-dl/weewx-DWD#78]
Mysteriöses Verhalten: Mußte heute für Arbeiten am Stromnetz meinen Raspberry frisch booten. Nach dem Neustart lief weewx zwar, konnt aber index.html.tmpl nicht mehr verarbeiten:
````
Okt 16 11:40:25 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: Evaluation of template /etc/weewx/skins/Seasons_DWD/index.html.tmpl failed with exception '<class 'TypeError'>'
Okt 16 11:40:25 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Seasons_DWD/index.html.tmpl
Okt 16 11:40:25 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: **** Reason: 'UnknownObsType' object is not subscriptable
Okt 16 11:40:25 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Okt 16 11:40:25 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 334, in generate
Okt 16 11:40:25 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Okt 16 11:40:25 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: ****    File "_etc_weewx_skins_Seasons_DWD_index_html_tmpl.py", line 223, in respond
Okt 16 11:40:25 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1708, in _handleCheetahInclude
Okt 16 11:40:25 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
Okt 16 11:40:25 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: ****    File "_etc_weewx_skins_Seasons_DWD_dwd_bio_inc.py", line 116, in respond
Okt 16 11:40:25 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/units.py", line 1096, in raw
Okt 16 11:40:25 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: ****      return self.value_t[0]
Okt 16 11:40:25 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: ****  TypeError: 'UnknownObsType' object is not subscriptable
Okt 16 11:40:33 imurr9 ntpd[667]: 131.188.3.220 local addr 192.168.178.49 -> <null>
Okt 16 11:41:09 imurr9 weewxd[813]: ERROR weewx.restx: StationRegistry: Failed to publish record 2024-10-16 11:40:00 CEST (1729071600): HTTP Error 429: TOO MANY REQUESTS
Okt 16 11:45:26 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: Evaluation of template /etc/weewx/skins/Seasons_DWD/index.html.tmpl failed with exception '<class 'TypeError'>'
Okt 16 11:45:26 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Seasons_DWD/index.html.tmpl
Okt 16 11:45:26 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: **** Reason: 'UnknownObsType' object is not subscriptable
Okt 16 11:45:26 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Okt 16 11:45:26 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 334, in generate
Okt 16 11:45:26 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Okt 16 11:45:26 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: ****    File "_etc_weewx_skins_Seasons_DWD_index_html_tmpl.py", line 223, in respond
Okt 16 11:45:26 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1708, in _handleCheetahInclude
Okt 16 11:45:26 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
Okt 16 11:45:26 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: ****    File "_etc_weewx_skins_Seasons_DWD_dwd_bio_inc.py", line 116, in respond
Okt 16 11:45:26 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/units.py", line 1096, in raw
Okt 16 11:45:26 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: ****      return self.value_t[0]
Okt 16 11:45:26 imurr9 weewxd[813]: ERROR weewx.cheetahgenerator: ****  TypeError: 'UnknownObsType' object is not subscriptable
Okt 16 1
````
Nach mehreren Versuchen hat's wieder geklappt, ohne daß ich irgendeine Skin-Datei geändert hätte.

ABER: Während der "Problemzeit" hat cron ein neues health-biowetter-I.inc runtergeladen. Daher könnte ich mir vorstellen, daß irgendein Sonderzeichen im alten health-biowetter-I.inc gestört haben mag. Leider ist das alte File mittlerweile überschrieben.

Die DWD-Skripte sind Stand von Anfang August 2024 (leider ohne Versionsinfo, da als zip downgeladen).

**Comment by olwaldi** [comment]
Danke für die schnelle Rückmeldung. Von der Fehlermeldung her hängt's wohl tatsächlich mit irgendwas Undefiniertem zusammen. Aber warum verschwindet der Fehler nach einiger Zeit? Ca. 20min nach dem Reboot funktionierte ja wieder Alles ohne Änderung (habe nur 2..3x weewx neu gestartet).Andererseits greife ich auch auf den ein oder anderen Wert .raw "ungeschützt" zu. Womöglich gabs noch gar keine health-Daten?Von meinem Huawei-Tablet gesendet-------- Originalnachricht --------Betreff: Re: [roe-dl/weewx-DWD] Nach reboot funktioniert cheetahgenerator bei bio Wetter nicht mehr (Issue #78)Von: roe-dl An: roe-dl/weewx-DWD Cc: olwaldi ,Author 
Das ist ein sehr schwer zu findender Fehler, der nichts mit der Erweiterung sondern etwas mit dem Template zu tun hat. Irgendwo innerhalb von index.html.tmpl gibt es einen Zugriff auf eine Meßgröße (observation type), die zu dieser Zeit nicht definiert war. Das kann zum Beispiel im Zusammenhang mit .raw sein. Alle diese Zugriffe muß man überall sauber mit  #if auf Gültigkeit prüfen oder in #try - #except - #end try einschließen. Das ist eine nervige Fleißarbeit, wenn die Datei lang ist.
Mit Sonderzeichen innerhalb der *.inc hat es auf jeden Fall nichts zu tun. Das sieht man an der Fehleremldung return self.value_t[0]. Dort wird versucht, auf den Zahlenwert einer Meßgröße zuzugreifen. Bei einer unbekannten Meßgröße (UnknownObsType) geht das natürlich nicht.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/roe-dl/weewx-DWD/issues/78#issuecomment-2416451437",
"url": "https://github.com/roe-dl/weewx-DWD/issues/78#issuecomment-2416451437",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by roe-dl** [comment]
> Wäre das ein möglicher Weg in meinem Skin (nicht ausprobiert, da Fehler ja nicht reproduzierbar):

Ich glaube, `$getVar` genügt nicht. Und wenn ich mich recht erinnere, kann man das `.raw` dort auch nicht in den String hineinnehmen sondern muß es hinten dranschreiben.

Die Varianten wären an Hand des genannten Beispiels wie folgt:

```
#try
#set $thermalstress = $current.biowetterExpectedThermalStress.raw
#except Exception
#set $thermalstress = None
#end try
```

oder

```
#if $current.biowetterExpectedThermalStress.has_data
#set $thermalstress = $current.biowetterExpectedThermalStress.raw
#else
#set $thermalstress = None
#end if
```

Wobei ich mir bei dem `has_data` nicht sicher bin.

> Ich nutze den Skin Seasons_DWD rein privat auf meinem Raspberry, d.h. weder die generierten HTMLs werden ins Internet exportiert, noch liegt der Skin Seasons_DWD irgendwo auf GIT. 

Wäre das nicht einmal ein Projekt, das von den ganz persönlichen Anteilen zu entschlacken und dann zu veröffentlichen? Gern auch als Beispiel unter weewx-DWD.

**Comment by olwaldi** [comment]
Danke für den Tip - nutze jetzt das #try.

Bzgl. Veröffentlichen: Da stellt sich mir die Henne-Ei-Frage, ob überhaupt jemand das modifizierte Seasons nutzen würde. Schließlich muß auch weewx selber gepatchet werden (meinen Erweiterungswunsch an weewx hat der Autor leider abgelehnt).

**Comment by roe-dl** [comment]
> Bzgl. Veröffentlichen: Da stellt sich mir die Henne-Ei-Frage, ob überhaupt jemand das modifizierte Seasons nutzen würde. 

Das weiß man nie vorher. Es sind schon Bücher zu Bestsellern geworden, die kein Verlag haben wollte. Oder umgekehrt zu Flops, die in renommierten Verlagen erschienen sind.

> Schließlich muß auch weewx selber gepatchet werden (meinen Erweiterungswunsch an weewx hat der Autor leider abgelehnt).

Das ist in der Tat eine Hürde. Und Tom Keffer von etwas zu überzeugen, ist wirklich keine leichte Aufgabe. Worin bestand denn der Erweiterungswunsch, wenn ich fragen darf?

**Comment by olwaldi** [comment]
> Das weiß man nie vorher. Es sind schon Bücher zu Bestsellern geworden, die kein Verlag haben wollte. Oder umgekehrt zu Flops, die in renommierten Verlagen erschienen sind.
>
Stimt natürlich.
 
> > Schließlich muß auch weewx selber gepatchet werden (meinen Erweiterungswunsch an weewx hat der Autor leider abgelehnt).
> 
> Das ist in der Tat eine Hürde. Und Tom Keffer von etwas zu überzeugen, ist wirklich keine leichte Aufgabe. Worin bestand denn der Erweiterungswunsch, wenn ich fragen darf?

Klar - siehe https://github.com/weewx/weewx/pull/905 Ist rückwärtskompatibel und sind nur 2..3 Zeilen Code.

**Comment by olwaldi** [comment]
Ursprünglich hatte ich nur vorgeschlagen, meine 2..3 Zeilen Code direkt zu übernehmen, um mir den Aufwand mit git/clonen u.Ä. zu ersparen. Stattdessen sollte ich seinen Entwicklungprozeß einhalten (was ich schon verstehe). Letzendlich hat er aber meine Änderung abgelehnt, obwohl (nachdem) ich alle seine Forderungen umgesetzt habe.

"Schlimm" ist das auch wieder nicht - so muß ich eben jede neue weewx-Version für meine Nutzung patchen.

Zurück zu meinem Skin Seasons_DWD: Kann ich gern irgendwohin (wohin?) uploaden und eine Anleitung zur Nutzung schreiben (crontab, weewx.conf, skins/Seasons_DWD/{.,dwd}). Aber ich möchte schon erneuten Aufwand mit git vermeiden.

**Comment by roe-dl** [comment]
Ok, es ist eher [#906](https://github.com/weewx/weewx/pull/906), wo Tom Keffers ablehnende Haltung sichtbar wird. Und ich erinnere mich jetzt, die damalige Diskussion mitbekommen zu haben. 

Beim FTP-Upload habe ich den Aufwand auch gescheut und nur bei mir eine kleine Änderung vorgenommen, um die Zeit zu verkürzen, die die Dateien wegen des Uploads nicht verfügbar sind. Nun habe ich mich aber doch aufgerafft und dafür eine [WeeWX-Erweiterung](https://github.com/roe-dl/weewx-sqlupload) geschrieben. Da muß ich niemanden fragen, dafür ist der Aufwand, alles allgemein benutzertauglich konfigurierbar zu machen, nicht zu unterschätzen. Rückfragen gab es dazu noch nicht, dafür aber Zweifel am Sinn der Sache im [Wetterstationsforum](https://www.wetterstationsforum.info/viewtopic.php?f=33&t=2390).

Ich mache dieses Issue dann mal zu.
