### ISSUE TITLE
dwd-mosmix, Parameter --belchertown, 3H Ansicht, fehlender Wert für Niederschlag?

### ISSUE THREAD

**Issue by hoetzgit** [roe-dl/weewx-DWD#8]
Hallo, ich glaube es fehlt der entsprechende Wert für den Niederschlag in der `forecast.json` für die 3H Ansicht.

**Comment by roe-dl** [comment]
Ich sehe es mir heute Abend an.

**Comment by hoetzgit** [comment]
Da schiebe ich gleich noch eine Frage hinterher ;-)
Macht es Sinn, Wetterwarnungen erst anzuzeigen, wenn sie die Gültigkeit erreicht haben?

Zeile `1319`:
`if al['timestamps']['begins']<now:`

**Comment by roe-dl** [comment]
Zum ursprünglichen Thema, der Niederschlagsangabe in der 3h-Vorhersage. Das Problem ist, daß der DWD den Wert der Regenwahrscheinlichkeit für 3 Stunden nicht liefert. Es gibt die Werte nur für 1h, 6h, 12h und 24h.

Wie löst man das?

Damit überhaupt etwas angezeigt wird, habe ich jetzt einmal das Maximum aus den 3 1h-Werten übergeben. Ob das die beste Lösung ist, wäre zu diskutieren.

**Comment by hoetzgit** [comment]
Ja, ich habe das jetzt auch gerade mit Warnungen, die ab 25.02. um 00:00 Uhr starten. Musste auch die Skin anpassen und zeige jetzt "gültig von" und "gültig bis" an. Habe für mich die Prüfung mal auf `if al['timestamps']['expires']>now:` gesetzt. Evtl könnte man das Startdatum zum aktuellen Zeitpunkt ins Verhältnis setzen und z.B. frühestens 6h vorher die Warnung anzeigen.

So, beim Thema Regen 3H kommt jetzt zum tragen, dass ich von Meteorologie keine Ahnung habe :-(
Evtl ein Durchschnitt aus den 1H Werten? Leider bin ich da völlig raus.

**Comment by roe-dl** [comment]
Nun wieder zu dem Thema mit den Warnungen: Wenn es verschiedene Meinungen gibt, macht man am besten eine Konfigurationsoption. Die lautet jetzt `include_advance_warnings` und gibt die Zahl der Sekunden an, die es in die Zukunft geben soll. Da hatte ich mich jetzt von dem Vorschlag mit den 6h leiten lassen.

commit 1a93421b61b51176d0de0a7eb7f3eccb7624e710

Bitte mal testen.

**Comment by roe-dl** [comment]
Beim Thema Regen kommt beim mir zum Tragen, daß ich in Statistik nicht sattelfest bin. Wenn die Regenwahrscheinlichkeit in der ersten Stunde 20% ist, in der zweiten 40% und in der dritten 30%, wie ist dann die Wahrscheinlichkeit über alle drei Stunden zusammengenommen? Ich weiß es nicht.

**Comment by hoetzgit** [comment]
Hinzu kommt noch, dass die Wahrscheinlichkeit in diesem Zusammenhang auch nicht so richtig aussagekräftig ist, finde ich jedenfalls.

Die Anpassung teste ich gleich morgen, evtl. noch als kleine Optimierung die Prüfung vor den Zuweisungen?

**Comment by hoetzgit** [comment]
Hallo, ich denke commit [1a92421](https://github.com/roe-dl/weewx-DWD/commit/1a93421b61b51176d0de0a7eb7f3eccb7624e710) sollte passen. 

Habe auch nochmal kontrolliert, ob alle in der Skin verwendeten Felder aus der forecast.json für die Vorhersage befüllt werden, mir ist kein Fehler aufgefallen. Ob alles inhaltlich korrekt befüllt ist, kann ich leider nicht beurteilen.  Kommt für den `[aqi]` Teil noch was? Sonst überschreibe ich den für mich evtl. mit Daten von AerisWeather.

Vielen Dank nochmals und ein schönes WE

**Comment by roe-dl** [comment]
Zwei Antworten zu AQI:

1. Da bin ich noch am Gucken, ob der DWD etwas Brauchbares liefert. Da es sich dabei aber nicht um eine Vorhersage sondern um einen Istzustand handelt, ist es vielleicht besser, es selbst zu messen, etwa mit einen airQ von Corant.
2. Für meinen Standort liefert Aeris die AQI-Daten, wenn man in die Datei hineinguckt, aus einem Ort namens Rudolice v horách, 66 km von meinem Standort entfernt. Das ist auf der anderen Seite des Erzgebirges, das wiederum eine Wetterscheide ist. Wie sinnvoll Aeris' AQI-Daten da sind, stelle ich einfach mal in den Raum.

Ich wünsche ebenfalls ein schönes Wochenende.

**Comment by hoetzgit** [comment]
Momentan nutze ich die Luftqualitätsdaten von OpenWeatherMap und (bisher) AerisWeather (Daten Station Weiden, ca. 10km)  zur Anzeige auf der Hauptseite. Aber ein Sensor ist unterwegs und ich werde aus Spass an der Freude selbst messen.
