### ISSUE TITLE
Frage zu den Tooltip-Daten via weewx-wdc Skin

### ISSUE THREAD

**Issue by Dondo11** [roe-dl/weewx-DWD#80]
Hallo roe-dl

Was ich bei den Tooltips beobachte:  Bei den Niederschlagsdaten wird in den Tooltips sowohl innerhalb desselben Tagesbalkens als auch bei den anderen Tagesbalken stets dieselbe Uhrzeit angezeigt.  In den anderen Diagrammen wechselt hingegen die Uhrzeit wie erwartet abhänging von der vertikalen Position.  Soll das so sein?

![TT 1](https://github.com/user-attachments/assets/4d834b21-887f-4876-bec4-76fbbad207e3)
![TT 2](https://github.com/user-attachments/assets/e4b2d221-48aa-421a-ac83-eb4c63d869e1)
![TT 3](https://github.com/user-attachments/assets/58615818-b024-4046-999a-f38ac67da8b4)

**Comment by roe-dl** [comment]
Das ist für mich schwierig zu beantworten. In den Daten selbst sind die Uhrzeiten enthalten. Es sind auch immer glatte Stunden. Möglicherweise hängt es damit zusammen, daß in dem Diagramm die Niederschlagswahrscheinlichkeit und die Bewölkung stündlich, die Niederschlagsmenge aber täglich aufgeführt ist. 

Mit der Konfiguration der WDC-Skin kenne ich mich leider nicht aus, so daß ich da keine kompetenten Aussagen machen kann. Ich kann erst einmal nur sagen, daß die vom weewx-DWD-Paket für die Darstellung von Diagrammen bereitgestellten Datenbankdateien die einzelnen Uhrzeiten enthalten.

**Comment by Dondo11** [comment]
Ich kann dort ja mal nachfragen.  Aber ja, an der Kombination von stündlichen mit täglichen Werten könnte das natürlich liegen.  Ist offenbar das einzige Diagramm, in dem diese "Mischung" vorkommt.

Danke erstmal!!

**Comment by Daveiano** [comment]
> an der Kombination von stündlichen mit täglichen Werten könnte das natürlich liegen

Ohne nochmals den Code gechecked zu haben, würde ich dem zustimmen - ich meine das war/ist noch ein Problem, das generell in kombinierten Charts (Balken + Liniendiagramm) auftritt. 

Gerne im weewx-wdc projekt ein Issue anlegen, sonst mache ich das ;)

**Comment by roe-dl** [comment]
https://github.com/Daveiano/weewx-wdc/issues/287
